
USE shl;
GO
CREATE UNIQUE INDEX UX_PlayerSeason
ON players(FirstName, LastName, TeamId, Season);

DECLARE @Skelleftea UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Skellefteå AIK');
DECLARE @Vaxjo UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Växjö Lakers');
DECLARE @Rogle UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Rögle BK');
DECLARE @Brynas UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Brynäs IF');
DECLARE @Frolunda UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Frölunda HC');
DECLARE @Linkoping UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Linköping HC');
DECLARE @Leksand UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Leksands IF');
DECLARE @Malmo UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Malmö Redhawks');
DECLARE @Lulea UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Luleå HF');
DECLARE @HV71 UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'HV71');
DECLARE @Timra UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Timrå IK');
DECLARE @Orebro UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Örebro HK');
DECLARE @Djurgarden UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Djurgårdens IF');
DECLARE @Farjestad UNIQUEIDENTIFIER = (SELECT TeamId FROM Team WHERE Name = 'Färjestad BK');

INSERT INTO players (FirstName, LastName, TeamId, Position, Nationality, Season, GamesPlayed)
VALUES
('Rasmus', 'Bergqvist', @Skelleftea, 'Back', 'Sverige', '25/26' ,40),
('Emil', 'Djuse', @Skelleftea, 'Back', 'Sverige', '25/26', 43),
('Måns', 'Forsfjäll', @Skelleftea, 'Back', 'Sverige', '25/26',7),
('Viktor', 'Grahn', @Skelleftea, 'Back', 'Sverige', '25/26', 52),
('Frans', 'Haara', @Skelleftea, 'Back', 'Sverige', '25/26', 30),
('Pontus', 'Johansson', @Skelleftea, 'Back', 'Sverige', '25/26', 51),
('Max', 'Krogdahl', @Skelleftea, 'Back', 'Norge', '25/26', 39),
('Arvid', 'Lundberg', @Skelleftea, 'Back', 'Sverige', '25/26', 50),
('Jonathan', 'Pudas', @Skelleftea, 'Back', 'Sverige', '25/26', 48),

('Mikkel', 'Aagaard', @Skelleftea, 'Forward', 'Danmark', '25/26', 50),
('Lars', 'Bryggman', @Skelleftea, 'Forward', 'Sverige', '25/26', 47),
('Jonathan', 'Davidsson', @Skelleftea, 'Forward', 'Sverige', '25/26', 40),
('Zeb', 'Forsfjäll', @Skelleftea, 'Forward', 'Sverige', '25/26', 49),
('Rickard', 'Hugg', @Skelleftea, 'Forward', 'Sverige', '25/26', 52),
('Jonathan', 'Johnsson', @Skelleftea, 'Forward', 'Sverige', '25/26', 52),
('Andreas', 'Johnsson', @Skelleftea, 'Forward', 'Sverige', '25/26', 52),
('Oscar', 'Lindberg', @Skelleftea, 'Forward', 'Sverige', '25/26', 52),
('Valter', 'Lindberg', @Skelleftea, 'Forward', 'Sverige', '25/26', 50),
('Pär', 'Lindholm', @Skelleftea, 'Forward', 'Sverige', '25/26', 47),
('Martin', 'Lundberg', @Skelleftea, 'Forward', 'Sverige', '25/26' , 9),
('Oliver', 'Okuliar', @Skelleftea, 'Forward', 'Slovakien', '25/26', 46),
('Victor', 'Stjernborg', @Skelleftea, 'Forward', 'Sverige', '25/26', 42),
('Oskar', 'Vuollet', @Skelleftea, 'Forward', 'Sverige', '25/26' , 51),
('Viktor', 'Klingsell', @Skelleftea, 'Forward', 'Sverige', '25/26' , 12),
('Elliot', 'Ölund', @Skelleftea, 'Forward', 'Sverige', '25/26' , 1),
('Zeb', 'Lindgren', @Skelleftea, 'Forward', 'Sverige', '25/26' , 2),
('Viggo', 'Nordlund', @Skelleftea, 'Forward', 'Sverige', '25/26' , 2),
('Theo', 'Landström', @Skelleftea, 'Forward', 'Sverige', '25/26' , 7),
('Victor', 'Laz', @Skelleftea, 'Forward', 'Sverige', '25/26', 13),

('Jere', 'Innala', @Frolunda, 'Forward', 'Finland', '25/26', 48),
('Arttu', 'Ruotsalainen', @Frolunda, 'Forward', 'Finland', '25/26', 50),
('Max', 'Lindholm', @Frolunda, 'Forward', 'Sverige', '25/26', 52),
('Ivar', 'Stenberg', @Frolunda, 'Forward', 'Sverige', '25/26', 43),
('Theodor', 'Niederbach', @Frolunda, 'Forward', 'Sverige', '25/26', 52),
('Filip', 'Cederqvist', @Frolunda, 'Forward', 'Sverige', '25/26', 50),
('Jacob', 'Peterson', @Frolunda, 'Forward', 'Sverige', '25/26', 43),
('Nicklas', 'Lasu', @Frolunda, 'Forward', 'Sverige', '25/26', 50),
('Max', 'Friberg', @Frolunda, 'Forward', 'Sverige', '25/26', 52),
('Linus', 'Weissbach', @Frolunda, 'Forward', 'Sverige', '25/26', 33),
('Noah', 'Dower-Nilsson', @Frolunda, 'Forward', 'Sverige', '25/26', 43),
('Erik', 'Thorell', @Frolunda, 'Forward', 'Sverige', '25/26', 20),
('Noah', 'Hasa', @Frolunda, 'Forward', 'Sverige', '25/26', 52),
('Isac', 'Born', @Frolunda, 'Forward', 'Sverige', '25/26', 40),
('Gian', 'Meier', @Frolunda, 'Forward', 'Schweiz', '25/26', 5),
('Axel', 'Brøngel-Larsson', @Frolunda, 'Forward', 'Sverige', '25/26', 1),
('Alfred', 'Persson', @Frolunda, 'Forward', 'Sverige', '25/26', 1),
('Bosse', 'Meijer', @Frolunda, 'Forward', 'Sverige', '25/26', 2),
('Mads', 'Kongsbak Klyvø', @Frolunda, 'Forward', 'Danmark', '25/26', 2),
('Måns', 'Toresson', @Frolunda, 'Forward', 'Sverige', '25/26', 16),
('Oskar', 'Wahlberg', @Frolunda, 'Forward', 'Sverige', '25/26', 16),
('Max', 'Westergård', @Frolunda, 'Forward', 'Finland', '25/26', 18),
('Gustav', 'Rydahl', @Frolunda, 'Forward', 'Sverige', '25/26', 0),

('Henrik', 'Tömmernes', @Frolunda, 'Back', 'Sverige', '25/26', 52),
('Linus', 'Högberg', @Frolunda, 'Back', 'Sverige', '25/26', 48),
('Dominik', 'Egli', @Frolunda, 'Back', 'Schweiz', '25/26', 46),
('Christian', 'Folin', @Frolunda, 'Back', 'Sverige', '25/26', 43),
('Samuel', 'Johannesson', @Frolunda, 'Back', 'Sverige', '25/26', 11),
('Filip', 'Hasa', @Frolunda, 'Back', 'Sverige', '25/26', 42),
('Isac', 'Heens', @Frolunda, 'Back', 'Sverige', '25/26', 51),
('Tom', 'Nilsson', @Frolunda, 'Back', 'Sverige', '25/26', 38),
('Eric', 'Norin', @Frolunda, 'Back', 'Sverige', '25/26', 8),

('Lucas', 'Elvenes', @Vaxjo, 'Forward', 'Sverige', '25/26', 51),
('Dennis', 'Rasmussen', @Vaxjo, 'Forward', 'Sverige', '25/26', 52),
('Reid', 'Gardiner', @Vaxjo, 'Forward', 'Kanada', '25/26', 49),
('Félix', 'Robert', @Vaxjo, 'Forward', 'Kanada', '25/26', 52),
('Dylan', 'McLaughlin', @Vaxjo, 'Forward', 'USA', '25/26', 52),
('Karl', 'Henriksson', @Vaxjo, 'Forward', 'Sverige', '25/26', 49),
('Eemeli', 'Suomi', @Vaxjo, 'Forward', 'Finland', '25/26', 36),
('Sebastian', 'Strandberg', @Vaxjo, 'Forward', 'Sverige', '25/26', 36),
('Manuel', 'Ågren', @Vaxjo, 'Forward', 'Sverige', '25/26', 43),
('Hugo', 'Gustafsson', @Vaxjo, 'Forward', 'Sverige', '25/26', 18),
('Ludvig', 'Nilsson', @Vaxjo, 'Forward', 'Sverige', '25/26', 47),
('Kalle', 'Kratz', @Vaxjo, 'Forward', 'Sverige', '25/26', 50),
('Ville', 'Svensson', @Vaxjo, 'Forward', 'Sverige', '25/26', 40),
('Erik', 'Andersson', @Vaxjo, 'Forward', 'Sverige', '25/26', 36),
('Morgan', 'Anderberg', @Vaxjo, 'Forward', 'Sverige', '25/26', 39),
('Otto', 'Koivula', @Vaxjo, 'Forward', 'Finland', '25/26', 5),
('Emon', 'Kulmala', @Vaxjo, 'Forward', 'Sverige', '25/26', 1),
('Olle', 'Karlsson', @Vaxjo, 'Forward', 'Sverige', '25/26', 5),
('Max', 'Isaksson', @Vaxjo, 'Forward', 'Sverige', '25/26', 3),
('Albin', 'Laksonen', @Vaxjo, 'Forward', 'Sverige', '25/26', 2),

('Joel', 'Persson', @Vaxjo, 'Back', 'Sverige', '25/26', 48),
('Brogan', 'Rafferty', @Vaxjo, 'Back', 'USA', '25/26', 48),
('Leo', 'Sahlin Wallenius', @Vaxjo, 'Back', 'Sverige', '25/26', 32),
('Keegan', 'Lowe', @Vaxjo, 'Back', 'Kanada', '25/26', 52),
('Brian', 'Cooper', @Vaxjo, 'Back', 'USA', '25/26', 45),
('Petter', 'Granberg', @Vaxjo, 'Back', 'Sverige', '25/26', 52),
('Elias', 'Rosén', @Vaxjo, 'Back', 'Sverige', '25/26', 39),
('Zach', 'Giuttari', @Vaxjo, 'Back', 'USA', '25/26', 38),
('Elias', 'Lindgren', @Vaxjo, 'Back', 'Sverige', '25/26', 1),
('Olle', 'Tideman', @Vaxjo, 'Back', 'Sverige', '25/26', 1),
('Liam', 'Pettersson', @Vaxjo, 'Back', 'Sverige', '25/26', 2),
('Ola', 'Palme', @Vaxjo, 'Back', 'Sverige', '25/26', 5),

('Felix', 'Nilsson', @Rogle, 'Forward', 'Sverige', '25/26', 52),
('Fredrik', 'Olofsson', @Rogle, 'Forward', 'Sverige', '25/26', 52),
('Leon', 'Bristedt', @Rogle, 'Forward', 'Sverige', '25/26', 49),
('Karson', 'Kuhlman', @Rogle, 'Forward', 'USA', '25/26', 52),
('Lubos', 'Horky', @Rogle, 'Forward', 'Tjeckien', '25/26', 46),
('Daniel', 'Zaar', @Rogle, 'Forward', 'Sverige', '25/26', 47),
('Linus', 'Sandin', @Rogle, 'Forward', 'Sverige', '25/26', 49),
('Albin', 'Sundsvik', @Rogle, 'Forward', 'Sverige', '25/26', 52),
('Dennis', 'Everberg', @Rogle, 'Forward', 'Sverige', '25/26', 48),
('Josh', 'Dickinson', @Rogle, 'Forward', 'Kanada', '25/26', 36),
('Anton', 'Bengtsson', @Rogle, 'Forward', 'Sverige', '25/26', 40),
('Simon', 'Zether', @Rogle, 'Forward', 'Sverige', '25/26', 40),
('Linus', 'Sjödin', @Rogle, 'Forward', 'Sverige', '25/26', 33),
('Marvin', 'Järvinen', @Rogle, 'Forward', 'Sverige', '25/26', 15),
('Johannes', 'Neumann', @Rogle, 'Forward', 'Österrike', '25/26', 3),
('Nils', 'Bartholdsson', @Rogle, 'Forward', 'Sverige', '25/26', 5),
('Love', 'Gath', @Rogle, 'Forward', 'Sverige', '25/26', 8),

('Isac', 'Solberg', @Rogle, 'Back', 'Sverige', '25/26', 42),
('Filip', 'Johansson', @Rogle, 'Back', 'Sverige', '25/26', 40),
('Mattias', 'Göransson', @Rogle, 'Back', 'Sverige', '25/26', 27),
('Calle', 'Själin', @Rogle, 'Back', 'Sverige', '25/26', 48),
('Paul', 'LaDue', @Rogle, 'Back', 'USA', '25/26', 47),
('Lucas', 'Ekeståhl Jonsson', @Rogle, 'Back', 'Sverige', '25/26', 52),
('Calvin', 'de Haan', @Rogle, 'Back', 'Kanada', '25/26', 46),
('Mark', 'Friedman', @Rogle, 'Back', 'Kanada', '25/26', 47),
('Gregor', 'Biber', @Rogle, 'Back', 'Österrike', '25/26', 38),
('Isak', 'Norlin', @Rogle, 'Back', 'Sverige', '25/26', 16),

('Viktor', 'Lodin', @Farjestad, 'Forward', 'Sverige', '25/26', 49),
('Luke', 'Philp', @Farjestad, 'Forward', 'Kanada', '25/26', 52),
('Per', 'Åslund', @Farjestad, 'Forward', 'Sverige', '25/26', 51),
('Radim', 'Zohorna', @Farjestad, 'Forward', 'Tjeckien', '25/26', 47),
('Marian', 'Studenic', @Farjestad, 'Forward', 'Slovakien', '25/26', 51),
('Joakim', 'Nygård', @Farjestad, 'Forward', 'Sverige', '25/26', 52),
('David', 'Tomasek', @Farjestad, 'Forward', 'Tjeckien', '25/26', 19),
('Joel', 'Kellman', @Farjestad, 'Forward', 'Sverige', '25/26', 45),
('Oskar', 'Steen', @Farjestad, 'Forward', 'Sverige', '25/26', 40),
('Linus', 'Johansson', @Farjestad, 'Forward', 'Sverige', '25/26', 35),
('Jack', 'Berglund', @Farjestad, 'Forward', 'Sverige', '25/26', 40),
('Christoffer', 'Jansson', @Farjestad, 'Forward', 'Sverige', '25/26', 48),
('Lucas', 'Forsell', @Farjestad, 'Forward', 'Sverige', '25/26', 50),
('Emil', 'Alba', @Farjestad, 'Forward', 'Sverige', '25/26', 45),
('Samuel', 'Eriksson', @Farjestad, 'Forward', 'Sverige', '25/26', 1),
('Rasmus', 'Röing', @Farjestad, 'Forward', 'Sverige', '25/26', 1),
('Åke', 'Stakkestad', @Farjestad, 'Forward', 'Sverige', '25/26', 1),
('Hampus', 'Plato', @Farjestad, 'Forward', 'Sverige', '25/26', 1),
('Måns', 'Gudmundsson', @Farjestad, 'Forward', 'Sverige', '25/26', 1),
('Oliver', 'Marcelius', @Farjestad, 'Forward', 'Sverige', '25/26', 2),
('Elias', 'Eriksson', @Farjestad, 'Forward', 'Sverige', '25/26', 4),
('Mikkel', 'Eriksen', @Farjestad, 'Forward', 'Norge', '25/26', 15),
('Wille', 'Johansson', @Farjestad, 'Forward', 'Sverige', '25/26', 18),

('Axel', 'Bergkvist', @Farjestad, 'Back', 'Sverige', '25/26', 52),
('Joe', 'Wahlund', @Farjestad, 'Back', 'Sverige', '25/26', 4),
('Adam', 'Ollas Mattsson', @Farjestad, 'Back', 'Sverige', '25/26', 52),
('Ronald', 'Knot', @Farjestad, 'Back', 'Tjeckien', '25/26', 33),
('Nick', 'Leivermann', @Farjestad, 'Back', 'USA', '25/26', 9),
('August', 'Tornberg', @Farjestad, 'Back', 'Sverige', '25/26', 6),
('Noel', 'Fransén', @Farjestad, 'Back', 'Sverige', '25/26', 13),
('Filip', 'Roos', @Farjestad, 'Back', 'Sverige', '25/26', 52),
('Magnus', 'Nygren', @Farjestad, 'Back', 'Sverige', '25/26', 47),
('Gabriel', 'Carlsson', @Farjestad, 'Back', 'Sverige', '25/26', 46),
('Albert', 'Wikman', @Farjestad, 'Back', 'Sverige', '25/26', 46),

('Jakob', 'Silfverberg', @Brynas, 'Forward', 'Sverige', '25/26', 52),
('Anton', 'Rödin', @Brynas, 'Forward', 'Sverige', '25/26', 48),
('Kieffer', 'Bellows', @Brynas, 'Forward', 'USA', '25/26', 52),
('Johan', 'Larsson', @Brynas, 'Forward', 'Sverige', '25/26', 51),
('Nicklas', 'Bäckström', @Brynas, 'Forward', 'Sverige', '25/26', 45),
('Bobby', 'Trivigno', @Brynas, 'Forward', 'USA', '25/26', 50),
('Oskar', 'Lindblom', @Brynas, 'Forward', 'Sverige', '25/26', 49),
('Lucas', 'Pettersson', @Brynas, 'Forward', 'Sverige', '25/26', 41),
('Linus', 'Ölund', @Brynas, 'Forward', 'Sverige', '25/26', 51),
('Axel', 'Jonsson-Fjällby', @Brynas, 'Forward', 'Sverige', '25/26', 52),
('Jack', 'Kopacka', @Brynas, 'Forward', 'USA', '25/26', 45),
('Tyler', 'Vesel', @Brynas, 'Forward', 'USA', '25/26', 51),
('Greg', 'Scott', @Brynas, 'Forward', 'Kanada', '25/26', 47),
('Gustav', 'Hillström', @Brynas, 'Forward', 'Sverige', '25/26', 27),
('Leo', 'Sundqvist', @Brynas, 'Forward', 'Sverige', '25/26', 11),
('Michal', 'Svrcek', @Brynas, 'Forward', 'Slovakien', '25/26', 12),

('Johannes', 'Kinnvall', @Brynas, 'Back', 'Sverige', '25/26', 51),
('Axel', 'Andersson', @Brynas, 'Back', 'Sverige', '25/26', 41),
('Michal', 'Kempny', @Brynas, 'Back', 'Tjeckien', '25/26', 39),
('Robert', 'Hägg', @Brynas, 'Back', 'Sverige', '25/26', 52),
('Mattias', 'Norlinder', @Brynas, 'Back', 'Sverige', '25/26', 48),
('Christian', 'Djoos', @Brynas, 'Back', 'Sverige', '25/26', 18),
('Simon', 'Bertilsson', @Brynas, 'Back', 'Sverige', '25/26', 26),
('Luke', 'Witkowski', @Brynas, 'Back', 'USA', '25/26', 27),
('Albin', 'Udd', @Brynas, 'Back', 'Sverige', '25/26', 1),
('Aron', 'Dahlqvist', @Brynas, 'Back', 'Sverige', '25/26', 14),
('Victor', 'Hedin Raftheim', @Brynas, 'Back', 'Sverige', '25/26', 28),

('Brian', 'O''Neill', @Lulea, 'Forward', 'USA', '25/26', 50),
('Markus', 'Nurmi', @Lulea, 'Forward', 'Finland', '25/26', 51),
('Filip', 'Eriksson', @Lulea, 'Forward', 'Sverige', '25/26', 52),
('Pontus', 'Andreasson', @Lulea, 'Forward', 'Sverige', '25/26', 52),
('Mathias', 'Bromé', @Lulea, 'Forward', 'Sverige', '25/26', 44),
('Isac', 'Hedqvist', @Lulea, 'Forward', 'Sverige', '25/26', 49),
('Anton', 'Levtchi', @Lulea, 'Forward', 'Finland', '25/26', 49),
('Linus', 'Omark', @Lulea, 'Forward', 'Sverige', '25/26', 29),
('Ben', 'Tardif', @Lulea, 'Forward', 'Kanada', '25/26', 32),
('Brendan', 'Shinnimin', @Lulea, 'Forward', 'Kanada', '25/26', 34),
('Eetu', 'Koivistoinen', @Lulea, 'Forward', 'Finland', '25/26', 50),
('Heikki', 'Liedes', @Lulea, 'Forward', 'Finland', '25/26', 50),
('Casper', 'Juustovaara Karlsson', @Lulea, 'Forward', 'Sverige', '25/26', 31),
('David', 'Granberg', @Lulea, 'Forward', 'Sverige', '25/26', 39),
('Jakob', 'Ihs-Wozniak', @Lulea, 'Forward', 'Sverige', '25/26', 17),
('Einar', 'Emanuelsson', @Lulea, 'Forward', 'Sverige', '25/26', 19),
('Jonas', 'Berglund', @Lulea, 'Forward', 'Sverige', '25/26', 0),

('Frédéric', 'Allard', @Lulea, 'Back', 'Kanada', '25/26', 50),
('Erik', 'Gustafsson', @Lulea, 'Back', 'Sverige', '25/26', 49),
('Jesper', 'Sellgren', @Lulea, 'Back', 'Sverige', '25/26', 52),
('Oskari', 'Laaksonen', @Lulea, 'Back', 'Finland', '25/26', 28),
('Otto', 'Leskinen', @Lulea, 'Back', 'Finland', '25/26', 32),
('Pontus', 'Själin', @Lulea, 'Back', 'Sverige', '25/26', 46),
('Oscar', 'Engsund', @Lulea, 'Back', 'Sverige', '25/26', 50),
('William', 'Håkansson', @Lulea, 'Back', 'Sverige', '25/26', 22),
('Oliwer', 'Sjöström', @Lulea, 'Back', 'Sverige', '25/26', 0),
('Edvin', 'Hammarlund', @Lulea, 'Back', 'Sverige', '25/26', 4),
('Neo', 'Hirsch', @Lulea, 'Back', 'Sverige', '25/26', 5),
('David', 'Thomasson', @Lulea, 'Back', 'Sverige', '25/26', 12),
('Kasper', 'Kotkansalo', @Lulea, 'Back', 'Finland', '25/26', 21),

('Janne', 'Kuokkanen', @Malmo, 'Forward', 'Finland', '25/26', 48),
('Carl', 'Persson', @Malmo, 'Forward', 'Sverige', '25/26', 49),
('Robin', 'Hanzl', @Malmo, 'Forward', 'Tjeckien', '25/26', 39),
('Lauri', 'Pajuniemi', @Malmo, 'Forward', 'Finland', '25/26', 51),
('Axel', 'Sundberg', @Malmo, 'Forward', 'Sverige', '25/26', 49),
('Fredrik', 'Händemark', @Malmo, 'Forward', 'Sverige', '25/26', 51),
('Linus', 'Öberg', @Malmo, 'Forward', 'Sverige', '25/26', 52),
('Petter', 'Vesterheim', @Malmo, 'Forward', 'Norge', '25/26', 51),
('Thomas', 'Berg-Paulsen', @Malmo, 'Forward', 'Norge', '25/26', 40),
('Isac', 'Nilsson', @Malmo, 'Forward', 'Sverige', '25/26', 44),
('William', 'von Barnekow', @Malmo, 'Forward', 'Sverige', '25/26', 45),
('Joona', 'Ikonen', @Malmo, 'Forward', 'Finland', '25/26', 52),
('Filip', 'Björkman', @Malmo, 'Forward', 'Sverige', '25/26', 27),
('Kalle', 'Hemström', @Malmo, 'Forward', 'Sverige', '25/26', 29),
('Isac', 'Born', @Malmo, 'Forward', 'Sverige', '25/26', 9),
('Freddie', 'Larsson', @Malmo, 'Forward', 'Sverige', '25/26', 3),
('Sebastian', 'Wännström', @Malmo, 'Forward', 'Sverige', '25/26', 3),
('Viktor', 'Olofsson', @Malmo, 'Forward', 'Sverige', '25/26', 4),
('Maximilian', 'Eisenmenger', @Malmo, 'Forward', 'Tyskland', '25/26', 26),

('Robin', 'Salo', @Malmo, 'Back', 'Finland', '25/26', 52),
('Topi', 'Niemelä', @Malmo, 'Back', 'Finland', '25/26', 52),
('Eemil', 'Viro', @Malmo, 'Back', 'Finland', '25/26', 52),
('Seth', 'Barton', @Malmo, 'Back', 'Kanada', '25/26', 47),
('Martin', 'Schreiber', @Malmo, 'Back', 'Sverige', '25/26', 50),
('Elia', 'Pedrotti', @Malmo, 'Back', 'Schweiz', '25/26', 20),
('Johan', 'Ivarsson', @Malmo, 'Back', 'Sverige', '25/26', 40),
('Isac', 'Pagels', @Malmo, 'Back', 'Sverige', '25/26', 0),
('Oliver', 'Rosvall', @Malmo, 'Back', 'Sverige', '25/26', 1),
('Carl-Johan', 'Lerby', @Malmo, 'Back', 'Sverige', '25/26', 1),
('Patrik', 'Norén', @Malmo, 'Back', 'Sverige', '25/26', 4),
('Joseph', 'Berger', @Malmo, 'Back', 'Sverige', '25/26', 15),
('Felix', 'Carell', @Malmo, 'Back', 'Sverige', '25/26', 31),

('Joe', 'Snively', @Djurgarden, 'Forward', 'USA', '25/26', 52),
('Charles', 'Hudon', @Djurgarden, 'Forward', 'Kanada', '25/26', 40),
('Anton', 'Frondell', @Djurgarden, 'Forward', 'Sverige', '25/26', 43),
('Victor', 'Eklund', @Djurgarden, 'Forward', 'Sverige', '25/26', 43),
('Mathias Emilio', 'Pettersen', @Djurgarden, 'Forward', 'Norge', '25/26', 48),
('Jacob', 'Josefson', @Djurgarden, 'Forward', 'Sverige', '25/26', 31),
('Viggo', 'Björck', @Djurgarden, 'Forward', 'Sverige', '25/26', 42),
('Marcus', 'Krüger', @Djurgarden, 'Forward', 'Sverige', '25/26', 40),
('Håvard Østrem', 'Salsten', @Djurgarden, 'Forward', 'Norge', '25/26', 49),
('David', 'Blomgren', @Djurgarden, 'Forward', 'Sverige', '25/26', 50),
('Oula', 'Palve', @Djurgarden, 'Forward', 'Finland', '25/26', 18),
('Jesse', 'Ylönen', @Djurgarden, 'Forward', 'Finland', '25/26', 24),
('Albin', 'Grewe', @Djurgarden, 'Forward', 'Sverige', '25/26', 37),
('Ludvig', 'Rensfeldt', @Djurgarden, 'Forward', 'Sverige', '25/26', 51),
('Daniel', 'Brodin', @Djurgarden, 'Forward', 'Sverige', '25/26', 24),
('William', 'Wåhlén', @Djurgarden, 'Forward', 'Sverige', '25/26', 2),
('Marcus', 'Nordmark', @Djurgarden, 'Forward', 'Sverige', '25/26', 8),
('Linus', 'Klasen', @Djurgarden, 'Forward', 'Sverige', '25/26', 9),
('Theo', 'Stockselius', @Djurgarden, 'Forward', 'Sverige', '25/26', 16),
('Arvid', 'Costmar', @Djurgarden, 'Forward', 'Sverige', '25/26', 29),
('Arvid', 'Drott', @Djurgarden, 'Forward', 'Sverige', '25/26', 1),
('Samuel', 'Solem', @Djurgarden, 'Forward', 'Norge', '25/26', 8),

('Joey', 'LaLeggia', @Djurgarden, 'Back', 'Kanada', '25/26', 50),
('Colby', 'Sissons', @Djurgarden, 'Back', 'Kanada', '25/26', 51),
('Gustav', 'Lindström', @Djurgarden, 'Back', 'Sverige', '25/26', 46),
('Philip', 'Holm', @Djurgarden, 'Back', 'Sverige', '25/26', 49),
('Jesper', 'Pettersson', @Djurgarden, 'Back', 'Sverige', '25/26', 51),
('Oliver', 'Kylington', @Djurgarden, 'Back', 'Sverige', '25/26', 25),
('Valtteri', 'Pulli', @Djurgarden, 'Back', 'Finland', '25/26', 30),
('August', 'Berg', @Djurgarden, 'Back', 'Sverige', '25/26', 23),
('Hugo', 'Blixt', @Djurgarden, 'Back', 'Sverige', '25/26', 36),
('Fred', 'Nord', @Djurgarden, 'Back', 'Sverige', '25/26', 1),

('Patrik', 'Karlkvist', @Orebro, 'Forward', 'Sverige', '25/26', 52),
('Patrik', 'Puistola', @Orebro, 'Forward', 'Finland', '25/26', 50),
('Kalle', 'Kossila', @Orebro, 'Forward', 'Finland', '25/26', 43),
('Noah', 'Steen', @Orebro, 'Forward', 'Norge', '25/26', 52),
('Egor', 'Polin', @Orebro, 'Forward', 'Sverige', '25/26', 50),
('Milton', 'Oscarson', @Orebro, 'Forward', 'Sverige', '25/26', 52),
('Teemu', 'Turunen', @Orebro, 'Forward', 'Finland', '25/26', 29),
('Christopher', 'Mastomäki', @Orebro, 'Forward', 'Sverige', '25/26', 52),
('William', 'Wikman', @Orebro, 'Forward', 'Sverige', '25/26', 49),
('Glenn', 'Gustafsson', @Orebro, 'Forward', 'Sverige', '25/26', 52),
('Sean', 'Malone', @Orebro, 'Forward', 'USA', '25/26', 31),
('Jesse', 'Ylönen', @Orebro, 'Forward', 'Finland', '25/26', 17),
('Sampo', 'Ranta', @Orebro, 'Forward', 'Finland', '25/26', 16),
('Melvin', 'Fernström', @Orebro, 'Forward', 'Sverige', '25/26', 36),
('Kalle', 'Miketinac', @Orebro, 'Forward', 'Sverige', '25/26', 17),
('Liam', 'Danielsson', @Orebro, 'Forward', 'Sverige', '25/26', 17),
('Svante', 'Sjödin', @Orebro, 'Forward', 'Sverige', '25/26', 26),
('Philip', 'Larsson', @Orebro, 'Forward', 'Sverige', '25/26', 1),
('Ludvig', 'Andersson', @Orebro, 'Forward', 'Sverige', '25/26', 2),
('Alexander', 'Command', @Orebro, 'Forward', 'Sverige', '25/26', 6),
('Niklas', 'Aaram-Olsen', @Orebro, 'Forward', 'Norge', '25/26', 16),

('David', 'Quenneville', @Orebro, 'Back', 'Kanada', '25/26', 52),
('Luke', 'Martin', @Orebro, 'Back', 'USA', '25/26', 50),
('Linus', 'Arnesson', @Orebro, 'Back', 'Sverige', '25/26', 50),
('Peetro', 'Seppälä', @Orebro, 'Back', 'Finland', '25/26', 51),
('Filip', 'Berglund', @Orebro, 'Back', 'Sverige', '25/26', 37),
('Gustav', 'Backström', @Orebro, 'Back', 'Sverige', '25/26', 52),
('Juuso', 'Vainio', @Orebro, 'Back', 'Finland', '25/26', 28),
('Theodor', 'Hallquisth', @Orebro, 'Back', 'Sverige', '25/26', 8),
('Niklas', 'Nilsson', @Orebro, 'Back', 'Sverige', '25/26', 29),
('Felix', 'Färhammar', @Orebro, 'Back', 'Sverige', '25/26', 2),
('Axel', 'Elfsson', @Orebro, 'Back', 'Sverige', '25/26', 6),

('Robin', 'Kovács', @Linkoping, 'Forward', 'Sverige', '25/26', 50),
('Eskild Bakke', 'Olsen', @Linkoping, 'Forward', 'Norge', '25/26', 51),
('Markus', 'Ljungh', @Linkoping, 'Forward', 'Sverige', '25/26', 52),
('Jakub', 'Vrána', @Linkoping, 'Forward', 'Tjeckien', '25/26', 46),
('Nick', 'Shore', @Linkoping, 'Forward', 'USA', '25/26', 50),
('Fredrik', 'Karlström', @Linkoping, 'Forward', 'Sverige', '25/26', 44),
('Christoffer', 'Ehn', @Linkoping, 'Forward', 'Sverige', '25/26', 52),
('Zion', 'Nybeck', @Linkoping, 'Forward', 'Sverige', '25/26', 52),
('Johan', 'Södergran', @Linkoping, 'Forward', 'Sverige', '25/26', 52),
('Ty', 'Rattie', @Linkoping, 'Forward', 'Kanada', '25/26', 30),
('Remi', 'Elie', @Linkoping, 'Forward', 'Kanada', '25/26', 7),
('Oliver', 'Johansson', @Linkoping, 'Forward', 'Sverige', '25/26', 41),
('Loke', 'Krantz', @Linkoping, 'Forward', 'Sverige', '25/26', 30),
('Johan', 'Johnsson', @Linkoping, 'Forward', 'Sverige', '25/26', 24),
('Adam', 'Hofbauer', @Linkoping, 'Forward', 'Sverige', '25/26', 52),
('Melvin', 'Nilsen', @Linkoping, 'Forward', 'Sverige', '25/26', 20),
('Oscar', 'Emanuelsson', @Linkoping, 'Forward', 'Sverige', '25/26', 1),
('Milton', 'Carpenhammar', @Linkoping, 'Forward', 'Sverige', '25/26', 3),
('William', 'Proos', @Linkoping, 'Forward', 'Sverige', '25/26', 4),
('Oscar', 'Lawner', @Linkoping, 'Forward', 'Sverige', '25/26', 6),
('Ludvig', 'Larsson', @Linkoping, 'Forward', 'Sverige', '25/26', 10),
('Oscar', 'Holmertz', @Linkoping, 'Forward', 'Sverige', '25/26', 11),

('David', 'Bernhardt', @Linkoping, 'Back', 'Sverige', '25/26', 46),
('Max', 'Martin', @Linkoping, 'Back', 'Kanada', '25/26', 52),
('Oscar', 'Fantenberg', @Linkoping, 'Back', 'Sverige', '25/26', 10),
('Rasmus', 'Rissanen', @Linkoping, 'Back', 'Finland', '25/26', 48),
('Theodor', 'Lennström', @Linkoping, 'Back', 'Sverige', '25/26', 18),
('Mikko', 'Kokkonen', @Linkoping, 'Back', 'Finland', '25/26', 44),
('Jonathan', 'Myrenberg', @Linkoping, 'Back', 'Sverige', '25/26', 48),
('Felix', 'Öhrqvist', @Linkoping, 'Back', 'Sverige', '25/26', 23),
('Wilhelm', 'Hasseluhn', @Linkoping, 'Back', 'Sverige', '25/26', 5),
('Edvin', 'Hammarlund', @Linkoping, 'Back', 'Sverige', '25/26', 7),
('Erik', 'Norén', @Linkoping, 'Back', 'Sverige', '25/26', 38),

('Jonathan', 'Dahlén', @Timra, 'Forward', 'Sverige', '25/26', 50),
('Emil', 'Pettersson', @Timra, 'Forward', 'Sverige', '25/26', 51),
('Eddie', 'Genborg', @Timra, 'Forward', 'Sverige', '25/26', 43),
('Anton', 'Lander', @Timra, 'Forward', 'Sverige', '25/26', 50),
('Sebastian', 'Hartmann', @Timra, 'Forward', 'Sverige', '25/26', 43),
('Anton', 'Heikkinen', @Timra, 'Forward', 'Sverige', '25/26', 49),
('Erik', 'Walli Walterholm', @Timra, 'Forward', 'Sverige', '25/26', 50),
('Anton', 'Wedin', @Timra, 'Forward', 'Sverige', '25/26', 32),
('Alfons', 'Freij', @Timra, 'Forward', 'Sverige', '25/26', 42),
('Ludvig', 'Levinsson', @Timra, 'Forward', 'Sverige', '25/26', 43),
('Linus', 'Eriksson', @Timra, 'Forward', 'Sverige', '25/26', 43),
('David', 'Lilja', @Timra, 'Forward', 'Sverige', '25/26', 49),
('Marcus', 'Westfält', @Timra, 'Forward', 'Sverige', '25/26', 49),
('Anton', 'Lundmark', @Timra, 'Forward', 'Sverige', '25/26', 23),
('Jeremy', 'Boyce', @Timra, 'Forward', 'Sverige', '25/26', 25),
('Magnus', 'Pääjärvi', @Timra, 'Forward', 'Sverige', '25/26', 52),
('Olle', 'Därth', @Timra, 'Forward', 'Sverige', '25/26', 3),
('William', 'Sörbrand', @Timra, 'Forward', 'Sverige', '25/26', 5),
('Edwin', 'Annerstedt', @Timra, 'Forward', 'Sverige', '25/26', 8),

('Lukas', 'Pilö', @Timra, 'Back', 'Sverige', '25/26', 39),
('Marcus', 'Hardegård', @Timra, 'Back', 'Sverige', '25/26', 41),
('Didrik', 'Strömberg', @Timra, 'Back', 'Sverige', '25/26', 48),
('Simon', 'Forsmark', @Timra, 'Back', 'Sverige', '25/26', 51),
('Linus', 'Nässén', @Timra, 'Back', 'Sverige', '25/26', 46),
('Albin', 'Sundin', @Timra, 'Back', 'Sverige', '25/26', 51),
('Per', 'Svensson', @Timra, 'Back', 'Sverige', '25/26', 43),
('Tim', 'Erixon', @Timra, 'Back', 'Sverige', '25/26', 0),
('Adrian', 'Thun-Hansson', @Timra, 'Back', 'Sverige', '25/26', 2),

('Jonathan', 'Ang', @HV71, 'Forward', 'Kanada', '25/26', 52),
('Riley', 'Woods', @HV71, 'Forward', 'Kanada', '25/26', 48),
('Lukas', 'Rousek', @HV71, 'Forward', 'Tjeckien', '25/26', 52),
('Justin', 'Kloos', @HV71, 'Forward', 'USA', '25/26', 50),
('Hugo', 'Pettersson', @HV71, 'Forward', 'Sverige', '25/26', 43),
('Aleksi', 'Heponiemi', @HV71, 'Forward', 'Finland', '25/26', 28),
('Nikola', 'Pasic', @HV71, 'Forward', 'Sverige', '25/26', 52),
('Mattias', 'Tedenby', @HV71, 'Forward', 'Sverige', '25/26', 48),
('Oskar', 'Stål Lyrenäs', @HV71, 'Forward', 'Sverige', '25/26', 41),
('Joona', 'Luoto', @HV71, 'Forward', 'Finland', '25/26', 30),
('Martin', 'Johnsen', @HV71, 'Forward', 'Norge', '25/26', 25),
('William', 'Nilsson Ignberg', @HV71, 'Forward', 'Sverige', '25/26', 31),
('Hampus', 'Eriksson', @HV71, 'Forward', 'Sverige', '25/26', 20),
('Linus', 'Lindström', @HV71, 'Forward', 'Sverige', '25/26', 44),
('Jamiro', 'Reber', @HV71, 'Forward', 'Schweiz', '25/26', 22),
('Eddie', 'Levin', @HV71, 'Forward', 'Sverige', '25/26', 2),
('Isac', 'Brännström', @HV71, 'Forward', 'Sverige', '25/26', 9),
('Victor', 'Laz', @HV71, 'Forward', 'Sverige', '25/26', 20),
('Oscar', 'Davidsson', @HV71, 'Forward', 'Sverige', '25/26', 15),
('Wille', 'Magnertoft', @HV71, 'Forward', 'Sverige', '25/26', 20),
('Gustav', 'Olhaver', @HV71, 'Forward', 'Sverige', '25/26', 1),
('Tim', 'Lindfors', @HV71, 'Forward', 'Sverige', '25/26', 1),
('Marcus', 'Limpar Lantz', @HV71, 'Forward', 'Sverige', '25/26', 1),
('Arvid', 'Degerstedt', @HV71, 'Forward', 'Sverige', '25/26', 2),
('Hampus', 'Karlsson', @HV71, 'Forward', 'Sverige', '25/26', 3),
('Noel', 'Skarby', @HV71, 'Forward', 'Sverige', '25/26', 6),

('Axel', 'Rindell', @HV71, 'Back', 'Finland', '25/26', 52),
('Hugo', 'Fransson', @HV71, 'Back', 'Sverige', '25/26', 52),
('Niklas', 'Hansson', @HV71, 'Back', 'Sverige', '25/26', 49),
('Andreas', 'Borgman', @HV71, 'Back', 'Sverige', '25/26', 35),
('Santeri', 'Hatakka', @HV71, 'Back', 'Finland', '25/26', 34),
('Olle', 'Alsing', @HV71, 'Back', 'Sverige', '25/26', 50),
('Lucas', 'Lagerberg Hoen', @HV71, 'Back', 'Sverige', '25/26', 43),
('Malte', 'Gustafsson', @HV71, 'Back', 'Sverige', '25/26', 27),
('Sigge', 'Lindh', @HV71, 'Back', 'Sverige', '25/26', 2),
('Oscar', 'Söderström', @HV71, 'Back', 'Sverige', '25/26', 2),
('Vashek', 'Blanár', @HV71, 'Back', 'Tjeckien', '25/26', 3),
('Karl', 'Annborn', @HV71, 'Back', 'Sverige', '25/26', 17),

('Lukas', 'Vejdemo', @Leksand, 'Forward', 'Sverige', '25/26', 51),
('Michael', 'Lindqvist', @Leksand, 'Forward', 'Sverige', '25/26', 31),
('Peter', 'Cehlárik', @Leksand, 'Forward', 'Slovakien', '25/26', 45),
('Max', 'Véronneau', @Leksand, 'Forward', 'Kanada', '25/26', 40),
('Nolan', 'Stevens', @Leksand, 'Forward', 'Kanada', '25/26', 49),
('Gabriel', 'Fortier', @Leksand, 'Forward', 'Kanada', '25/26', 44),
('Oskar', 'Lang', @Leksand, 'Forward', 'Sverige', '25/26', 49),
('Tinus Luc', 'Koblar', @Leksand, 'Forward', 'Norge', '25/26', 47),
('Andro', 'Kaderli', @Leksand, 'Forward', 'Schweiz', '25/26', 49),
('Kalle', 'Östman', @Leksand, 'Forward', 'Sverige', '25/26', 41),
('Arvid', 'Eljas', @Leksand, 'Forward', 'Sverige', '25/26', 41),
('Fred', 'Nilsson', @Leksand, 'Forward', 'Sverige', '25/26', 45),
('Marcus', 'Karlberg', @Leksand, 'Forward', 'Sverige', '25/26', 44),
('Wiktor', 'Nilsson', @Leksand, 'Forward', 'Sverige', '25/26', 45),
('Jon', 'Knuts', @Leksand, 'Forward', 'Sverige', '25/26', 39),
('Zaki', 'Crookes', @Leksand, 'Forward', 'Sverige', '25/26', 20),
('Viggo', 'Lidén', @Leksand, 'Forward', 'Sverige', '25/26', 0),
('Jonas', 'Lagerberg Hoen', @Leksand, 'Forward', 'Sverige', '25/26', 2),
('Pax', 'Kleffner', @Leksand, 'Forward', 'Sverige', '25/26', 2),
('August', 'Lissel', @Leksand, 'Forward', 'Sverige', '25/26', 14),
('Dennis', 'Altörn', @Leksand, 'Forward', 'Sverige', '25/26', 19),

('Olle', 'Strandell', @Leksand, 'Back', 'Sverige', '25/26', 52),
('Anton', 'Johansson', @Leksand, 'Back', 'Sverige', '25/26', 42),
('Matt', 'Caito', @Leksand, 'Back', 'USA', '25/26', 50),
('Joonas', 'Lyytinen', @Leksand, 'Back', 'Finland', '25/26', 42),
('Alexander', 'Lundqvist', @Leksand, 'Back', 'Sverige', '25/26', 51),
('Stefan', 'Milosevic', @Leksand, 'Back', 'Sverige', '25/26', 48),
('Victor', 'Johansson', @Leksand, 'Back', 'Sverige', '25/26', 10),
('Rocky', 'Langvardt', @Leksand, 'Back', 'Sverige', '25/26', 24);
GO
