USE shl;
GO

INSERT INTO PlayerStats
    (
    PlayerId,
    Season,
    Competition,
    GamesPlayed,
    Goals,
    Assists,
    Points,
    PenaltyMinutes
    )
SELECT
    p.PlayerId,
    '25/26',
    ps.Season,
    TRY_CAST(ps.GamesPlayed AS INT),
    TRY_CAST(ps.Goals AS INT),
    TRY_CAST(ps.Assists AS INT),
    TRY_CAST(ps.Goals AS INT) + TRY_CAST(ps.Assists AS INT),
    TRY_CAST(ps.PenaltyMinutes AS INT)
FROM (
    VALUES
        -- SKELLEFTEÅ     
        ('Rasmus', 'Bergqvist', 'Skellefteå AIK', 40, 0, 4, 4, 18, 'Regular'),
        ('Emil', 'Djuse', 'Skellefteå AIK', 43, 0, 12, 12, 35, 'Regular'),
        ('Emil', 'Djuse', 'Skellefteå AIK', 15, 4, 4, 8, 4, 'Playoff'),
        ('Måns', 'Forsfjäll', 'Skellefteå AIK', 7, 0, 1, 1, 2, 'Regular'),
        ('Måns', 'Forsfjäll', 'Skellefteå AIK', 15, 0, 1, 1, 0, 'Playoff'),
        ('Viktor', 'Grahn', 'Skellefteå AIK', 52, 3, 15, 18, 6, 'Regular'),
        ('Viktor', 'Grahn', 'Skellefteå AIK', 15, 3, 3, 6, 0, 'Playoff'),
        ('Frans', 'Haara', 'Skellefteå AIK', 30, 3, 4, 7, 4, 'Regular'),
        ('Frans', 'Haara', 'Skellefteå AIK', 4, 0, 1, 1, 6, 'Playoff'),
        ('Pontus', 'Johansson', 'Skellefteå AIK', 51, 6, 19, 25, 26, 'Regular'),
        ('Pontus', 'Johansson', 'Skellefteå AIK', 15, 4, 6, 10, 6, 'Playoff'),
        ('Max', 'Krogdahl', 'Skellefteå AIK', 39, 2, 9, 11, 67, 'Regular'),
        ('Max', 'Krogdahl', 'Skellefteå AIK', 15, 0, 6, 6, 41, 'Playoff'),
        ('Arvid', 'Lundberg', 'Skellefteå AIK', 50, 8, 13, 21, 16, 'Regular'),
        ('Arvid', 'Lundberg', 'Skellefteå AIK', 15, 1, 3, 4, 8, 'Playoff'),
        ('Jonathan', 'Pudas', 'Skellefteå AIK', 48, 16, 31, 47, 36, 'Regular'),
        ('Jonathan', 'Pudas', 'Skellefteå AIK', 11, 1, 5, 6, 4, 'Playoff'),
        ('Mikkel', 'Aagaard', 'Skellefteå AIK', 50, 20, 23, 43, 14, 'Regular'),
        ('Mikkel', 'Aagaard', 'Skellefteå AIK', 15, 4, 4, 8, 10, 'Playoff'),
        ('Lars', 'Bryggman', 'Skellefteå AIK', 47, 10, 11, 21, 22, 'Regular'),
        ('Lars', 'Bryggman', 'Skellefteå AIK', 15, 5, 4, 9, 2, 'Playoff'),
        ('Jonathan', 'Davidsson', 'Skellefteå AIK', 40, 4, 6, 10, 10, 'Regular'),
        ('Jonathan', 'Davidsson', 'Skellefteå AIK', 14, 0, 4, 4, 4, 'Playoff'),
        ('Zeb', 'Forsfjäll', 'Skellefteå AIK', 49, 3, 4, 7, 8, 'Regular'),
        ('Zeb', 'Forsfjäll', 'Skellefteå AIK', 15, 0, 4, 4, 6, 'Playoff'),
        ('Rickard', 'Hugg', 'Skellefteå AIK', 52, 20, 36, 56, 12, 'Regular'),
        ('Rickard', 'Hugg', 'Skellefteå AIK', 15, 3, 3, 6, 6, 'Playoff'),
        ('Jonathan', 'Johnsson', 'Skellefteå AIK', 52, 9, 21, 30, 14, 'Regular'),
        ('Jonathan', 'Johnsson', 'Skellefteå AIK', 15, 2, 5, 7, 8, 'Playoff'),
        ('Andreas', 'Johnsson', 'Skellefteå AIK', 52, 13, 12, 25, 32, 'Regular'),
        ('Andreas', 'Johnsson', 'Skellefteå AIK', 15, 3, 8, 11, 4, 'Playoff'),
        ('Oscar', 'Lindberg', 'Skellefteå AIK', 52, 30, 37, 67, 52, 'Regular'),
        ('Oscar', 'Lindberg', 'Skellefteå AIK', 15, 5, 9, 14, 8, 'Playoff'),
        ('Valter', 'Lindberg', 'Skellefteå AIK', 50, 5, 12, 17, 8, 'Regular'),
        ('Valter', 'Lindberg', 'Skellefteå AIK', 13, 1, 7, 8, 2, 'Playoff'),
        ('Pär', 'Lindholm', 'Skellefteå AIK', 47, 6, 18, 24, 18, 'Regular'),
        ('Pär', 'Lindholm', 'Skellefteå AIK', 9, 2, 5, 7, 25, 'Playoff'),
        ('Martin', 'Lundberg', 'Skellefteå AIK', 9, 0, 0, 0, 4, 'Regular'),
        ('Martin', 'Lundberg', 'Skellefteå AIK', 15, 0, 1, 1, 2, 'Playoff'),
        ('Oliver', 'Okuliar', 'Skellefteå AIK', 46, 15, 14, 29, 38, 'Regular'),
        ('Oliver', 'Okuliar', 'Skellefteå AIK', 15, 6, 7, 13, 6, 'Playoff'),
        ('Victor', 'Stjernborg', 'Skellefteå AIK', 42, 5, 7, 12, 8, 'Regular'),
        ('Victor', 'Stjernborg', 'Skellefteå AIK', 15, 6, 2, 8, 2, 'Playoff'),
        ('Oskar', 'Vuollet', 'Skellefteå AIK', 51, 3, 4, 7, 6, 'Regular'),
        ('Oskar', 'Vuollet', 'Skellefteå AIK', 9, 2, 0, 2, 25, 'Playoff'),
        ('Viktor', 'Klingsell', 'Skellefteå AIK', 12, 1, 0, 1, 0, 'Regular'),
        ('Elliot', 'Ölund', 'Skellefteå AIK', 1, 0, 0, 0, 0, 'Regular'),
        ('Zeb', 'Lindgren', 'Skellefteå AIK', 2, 0, 0, 0, 0, 'Regular'),
        ('Viggo', 'Nordlund', 'Skellefteå AIK', 2, 0, 0, 0, 0, 'Regular'),
        ('Theo', 'Landström', 'Skellefteå AIK', 7, 0, 0, 0, 0, 'Regular'),
        ('Victor', 'Laz', 'Skellefteå AIK', 13, 0, 2, 2, 0, 'Regular'),

        -- LULEÅ
        ('Brian', 'O''Neill', 'Luleå HF', 50, 11, 25, 36, 18, 'Regular'),
        ('Brian', 'O''Neill', 'Luleå HF', 14, 1, 5, 6, 31, 'Playoff'),
        ('Markus', 'Nurmi', 'Luleå HF', 51, 15, 17, 32, 50, 'Regular'),
        ('Markus', 'Nurmi', 'Luleå HF', 14, 0, 1, 1, 30, 'Playoff'),
        ('Frédéric', 'Allard', 'Luleå HF', 50, 7, 25, 32, 51, 'Regular'),
        ('Frédéric', 'Allard', 'Luleå HF', 8, 1, 1, 2, 6, 'Playoff'),
        ('Filip', 'Eriksson', 'Luleå HF', 52, 15, 14, 29, 6, 'Regular'),
        ('Filip', 'Eriksson', 'Luleå HF', 9, 0, 1, 1, 0, 'Playoff'),
        ('Pontus', 'Andreasson', 'Luleå HF', 52, 10, 17, 27, 34, 'Regular'),
        ('Pontus', 'Andreasson', 'Luleå HF', 14, 1, 5, 6, 10, 'Playoff'),
        ('Erik', 'Gustafsson', 'Luleå HF', 49, 8, 15, 23, 18, 'Regular'),
        ('Erik', 'Gustafsson', 'Luleå HF', 14, 1, 1, 2, 6, 'Playoff'),
        ('Mathias', 'Bromé', 'Luleå HF', 44, 11, 11, 22, 8, 'Regular'),
        ('Mathias', 'Bromé', 'Luleå HF', 14, 3, 5, 8, 0, 'Playoff'),
        ('Isac', 'Hedqvist', 'Luleå HF', 49, 10, 10, 20, 22, 'Regular'),
        ('Isac', 'Hedqvist', 'Luleå HF', 14, 4, 4, 8, 10, 'Playoff'),
        ('Anton', 'Levtchi', 'Luleå HF', 49, 7, 11, 18, 18, 'Regular'),
        ('Anton', 'Levtchi', 'Luleå HF', 14, 6, 2, 8, 12, 'Playoff'),
        ('Jesper', 'Sellgren', 'Luleå HF', 52, 3, 14, 17, 8, 'Regular'),
        ('Jesper', 'Sellgren', 'Luleå HF', 7, 1, 5, 6, 2, 'Playoff'),
        ('Oskari', 'Laaksonen', 'Luleå HF', 28, 5, 11, 16, 18, 'Regular'),
        ('Oskari', 'Laaksonen', 'Luleå HF', 12, 0, 9, 9, 39, 'Playoff'),
        ('Linus', 'Omark', 'Luleå HF', 29, 5, 11, 16, 12, 'Regular'),
        ('Linus', 'Omark', 'Luleå HF', 14, 1, 7, 8, 18, 'Playoff'),
        ('Ben', 'Tardif', 'Luleå HF', 32, 10, 4, 14, 4, 'Regular'),
        ('Ben', 'Tardif', 'Luleå HF', 14, 2, 0, 2, 2, 'Playoff'),
        ('Brendan', 'Shinnimin', 'Luleå HF', 34, 5, 6, 11, 28, 'Regular'),
        ('Brendan', 'Shinnimin', 'Luleå HF', 14, 4, 3, 7, 37, 'Playoff'),
        ('Eetu', 'Koivistoinen', 'Luleå HF', 50, 5, 6, 11, 33, 'Regular'),
        ('Eetu', 'Koivistoinen', 'Luleå HF', 14, 4, 0, 4, 24, 'Playoff'),
        ('Otto', 'Leskinen', 'Luleå HF', 32, 3, 6, 9, 12, 'Regular'),
        ('Otto', 'Leskinen', 'Luleå HF', 14, 0, 2, 2, 31, 'Playoff'),
        ('Heikki', 'Liedes', 'Luleå HF', 50, 2, 5, 7, 22, 'Regular'),
        ('Heikki', 'Liedes', 'Luleå HF', 14, 0, 0, 0, 6, 'Playoff'),
        ('Casper', 'Juustovaara Karlsson', 'Luleå HF', 31, 4, 2, 6, 6, 'Regular'),
        ('Casper', 'Juustovaara Karlsson', 'Luleå HF', 3, 0, 0, 0, 0, 'Playoff'),
        ('David', 'Granberg', 'Luleå HF', 39, 1, 4, 5, 4, 'Regular'),
        ('David', 'Granberg', 'Luleå HF', 12, 0, 0, 0, 0, 'Playoff'),
        ('Pontus', 'Själin', 'Luleå HF', 46, 0, 5, 5, 12, 'Regular'),
        ('Pontus', 'Själin', 'Luleå HF', 13, 0, 1, 1, 25, 'Playoff'),
        ('Oscar', 'Engsund', 'Luleå HF', 50, 0, 3, 3, 16, 'Regular'),
        ('Oscar', 'Engsund', 'Luleå HF', 14, 1, 0, 1, 29, 'Playoff'),
        ('Jakob', 'Ihs-Wozniak', 'Luleå HF', 17, 2, 0, 2, 2, 'Regular'),
        ('Einar', 'Emanuelsson', 'Luleå HF', 19, 0, 2, 2, 0, 'Regular'),
        ('William', 'Håkansson', 'Luleå HF', 22, 0, 2, 2, 8, 'Regular'),
        ('William', 'Håkansson', 'Luleå HF', 9, 0, 0, 0, 0, 'Playoff'),
        ('Jonas', 'Berglund', 'Luleå HF', 0, 0, 0, 0, 0, 'Regular'),
        ('Oliwer', 'Sjöström', 'Luleå HF', 0, 0, 0, 0, 0, 'Regular'),
        ('Oliwer', 'Sjöström', 'Luleå HF', 6, 0, 0, 0, 0, 'Playoff'),
        ('Edvin', 'Hammarlund', 'Luleå HF', 4, 0, 0, 0, 0, 'Regular'),
        ('Neo', 'Hirsch', 'Luleå HF', 5, 0, 0, 0, 0, 'Regular'),
        ('David', 'Thomasson', 'Luleå HF', 12, 0, 0, 0, 0, 'Regular'),
        ('Kasper', 'Kotkansalo', 'Luleå HF', 21, 0, 0, 0, 6, 'Regular'),

        -- FRÖLUNDA
        ('Jere', 'Innala', 'Frölunda HC', 48, 22, 18, 40, 16, 'Regular'),
        ('Jere', 'Innala', 'Frölunda HC', 6, 2, 1, 3, 6, 'Playoff'),
        ('Arttu', 'Ruotsalainen', 'Frölunda HC', 50, 15, 21, 36, 18, 'Regular'),
        ('Arttu', 'Ruotsalainen', 'Frölunda HC', 6, 1, 3, 4, 0, 'Playoff'),
        ('Henrik', 'Tömmernes', 'Frölunda HC', 52, 6, 29, 35, 20, 'Regular'),
        ('Henrik', 'Tömmernes', 'Frölunda HC', 4, 0, 2, 2, 8, 'Playoff'),
        ('Max', 'Lindholm', 'Frölunda HC', 52, 17, 16, 33, 22, 'Regular'),
        ('Max', 'Lindholm', 'Frölunda HC', 6, 0, 3, 3, 2, 'Playoff'),
        ('Ivar', 'Stenberg', 'Frölunda HC', 43, 11, 22, 33, 6, 'Regular'),
        ('Ivar', 'Stenberg', 'Frölunda HC', 6, 0, 4, 4, 4, 'Playoff'),
        ('Theodor', 'Niederbach', 'Frölunda HC', 52, 13, 19, 32, 16, 'Regular'),
        ('Theodor', 'Niederbach', 'Frölunda HC', 6, 1, 1, 2, 2, 'Playoff'),
        ('Filip', 'Cederqvist', 'Frölunda HC', 50, 15, 14, 29, 14, 'Regular'),
        ('Filip', 'Cederqvist', 'Frölunda HC', 6, 3, 3, 6, 25, 'Playoff'),
        ('Linus', 'Högberg', 'Frölunda HC', 48, 8, 16, 24, 10, 'Regular'),
        ('Linus', 'Högberg', 'Frölunda HC', 6, 0, 1, 1, 4, 'Playoff'),
        ('Dominik', 'Egli', 'Frölunda HC', 46, 3, 17, 20, 24, 'Regular'),
        ('Dominik', 'Egli', 'Frölunda HC', 5, 1, 1, 2, 33, 'Playoff'),
        ('Jacob', 'Peterson', 'Frölunda HC', 43, 9, 10, 19, 14, 'Regular'),
        ('Jacob', 'Peterson', 'Frölunda HC', 6, 1, 3, 4, 0, 'Playoff'),
        ('Nicklas', 'Lasu', 'Frölunda HC', 50, 7, 12, 19, 22, 'Regular'),
        ('Nicklas', 'Lasu', 'Frölunda HC', 6, 1, 0, 1, 2, 'Playoff'),
        ('Max', 'Friberg', 'Frölunda HC', 52, 5, 14, 19, 10, 'Regular'),
        ('Max', 'Friberg', 'Frölunda HC', 6, 2, 1, 3, 2, 'Playoff'),
        ('Linus', 'Weissbach', 'Frölunda HC', 33, 5, 12, 17, 2, 'Regular'),
        ('Linus', 'Weissbach', 'Frölunda HC', 1, 0, 1, 1, 0, 'Playoff'),
        ('Noah', 'Dower-Nilsson', 'Frölunda HC', 48, 6, 10, 16, 10, 'Regular'),
        ('Noah', 'Dower-Nilsson', 'Frölunda HC', 6, 2, 2, 4, 2, 'Playoff'),
        ('Erik', 'Thorell', 'Frölunda HC', 20, 4, 12, 16, 0, 'Regular'),
        ('Erik', 'Thorell', 'Frölunda HC', 6, 0, 0, 0, 0, 'Playoff'),
        ('Noah', 'Hasa', 'Frölunda HC', 52, 7, 7, 14, 8, 'Regular'),
        ('Noah', 'Hasa', 'Frölunda HC', 4, 0, 0, 0, 2, 'Playoff'),
        ('Isac', 'Heens', 'Frölunda HC', 51, 1, 10, 11, 12, 'Regular'),
        ('Isac', 'Heens', 'Frölunda HC', 4, 0, 0, 0, 0, 'Playoff'),
        ('Tom', 'Nilsson', 'Frölunda HC', 38, 2, 8, 10, 14, 'Regular'),
        ('Tom', 'Nilsson', 'Frölunda HC', 6, 1, 2, 3, 4, 'Playoff'),
        ('Christian', 'Folin', 'Frölunda HC', 43, 1, 4, 5, 14, 'Regular'),
        ('Christian', 'Folin', 'Frölunda HC', 6, 0, 1, 1, 4, 'Playoff'),
        ('Samuel', 'Johannesson', 'Frölunda HC', 11, 2, 2, 4, 4, 'Regular'),
        ('Samuel', 'Johannesson', 'Frölunda HC', 6, 0, 0, 0, 0, 'Playoff'),
        ('Filip', 'Hasa', 'Frölunda HC', 42, 2, 1, 3, 16, 'Regular'),
        ('Filip', 'Hasa', 'Frölunda HC', 4, 0, 0, 0, 2, 'Playoff'),
        ('Isac', 'Born', 'Frölunda HC', 40, 0, 3, 3, 2, 'Regular'),
        ('Isac', 'Born', 'Frölunda HC', 5, 0, 0, 0, 0, 'Playoff'),
        ('Gian', 'Meier', 'Frölunda HC', 5, 0, 1, 1, 4, 'Regular'),
        ('Gustav', 'Rydahl', 'Frölunda HC', 0, 0, 0, 0, 0, 'Regular'),
        ('Axel', 'Brøngel-Larsson', 'Frölunda HC', 1, 0, 0, 0, 0, 'Regular'),
        ('Alfred', 'Persson', 'Frölunda HC', 1, 0, 0, 0, 0, 'Regular'),
        ('Bosse', 'Meijer', 'Frölunda HC', 2, 0, 0, 0, 0, 'Regular'),
        ('Mads', 'Kongsbak Klyvø', 'Frölunda HC', 2, 0, 0, 0, 0, 'Regular'),
        ('Eric', 'Norin', 'Frölunda HC', 8, 0, 0, 0, 0, 'Regular'),
        ('Måns', 'Toresson', 'Frölunda HC', 16, 0, 0, 0, 0, 'Regular'),
        ('Oskar', 'Wahlberg', 'Frölunda HC', 16, 0, 0, 0, 2, 'Regular'),
        ('Oskar', 'Wahlberg', 'Frölunda HC', 1, 0, 0, 0, 0, 'Playoff'),
        ('Max', 'Westergård', 'Frölunda HC', 18, 0, 0, 0, 2, 'Regular'),
        ('Max', 'Westergård', 'Frölunda HC', 2, 0, 0, 0, 0, 'Playoff'),

        -- VÄXJÖ
        ('Lucas', 'Elvenes', 'Växjö Lakers', 51, 12, 38, 50, 14, 'Regular'),
        ('Lucas', 'Elvenes', 'Växjö Lakers', 10, 2, 7, 9, 2, 'Playoff'),
        ('Joel', 'Persson', 'Växjö Lakers', 48, 8, 36, 44, 28, 'Regular'),
        ('Joel', 'Persson', 'Växjö Lakers', 10, 0, 9, 9, 8, 'Playoff'),
        ('Dennis', 'Rasmussen', 'Växjö Lakers', 52, 20, 17, 37, 14, 'Regular'),
        ('Dennis', 'Rasmussen', 'Växjö Lakers', 10, 3, 1, 4, 29, 'Playoff'),
        ('Brogan', 'Rafferty', 'Växjö Lakers', 48, 12, 24, 36, 6, 'Regular'),
        ('Brogan', 'Rafferty', 'Växjö Lakers', 9, 2, 4, 6, 4, 'Playoff'),
        ('Reid', 'Gardiner', 'Växjö Lakers', 49, 15, 15, 30, 12, 'Regular'),
        ('Reid', 'Gardiner', 'Växjö Lakers', 10, 4, 0, 4, 2, 'Playoff'),
        ('Félix', 'Robert', 'Växjö Lakers', 52, 16, 8, 24, 34, 'Regular'),
        ('Félix', 'Robert', 'Växjö Lakers', 10, 1, 3, 4, 2, 'Playoff'),
        ('Dylan', 'McLaughlin', 'Växjö Lakers', 52, 11, 11, 22, 4, 'Regular'),
        ('Dylan', 'McLaughlin', 'Växjö Lakers', 10, 1, 2, 3, 0, 'Playoff'),
        ('Karl', 'Henriksson', 'Växjö Lakers', 49, 12, 7, 19, 49, 'Regular'),
        ('Karl', 'Henriksson', 'Växjö Lakers', 10, 2, 4, 6, 0, 'Playoff'),
        ('Eemeli', 'Suomi', 'Växjö Lakers', 36, 6, 8, 14, 18, 'Regular'),
        ('Eemeli', 'Suomi', 'Växjö Lakers', 9, 3, 0, 3, 27, 'Playoff'),
        ('Sebastian', 'Strandberg', 'Växjö Lakers', 36, 6, 7, 13, 8, 'Regular'),
        ('Manuel', 'Ågren', 'Växjö Lakers', 43, 4, 9, 13, 20, 'Regular'),
        ('Manuel', 'Ågren', 'Växjö Lakers', 10, 2, 3, 5, 6, 'Playoff'),
        ('Leo', 'Sahlin Wallenius', 'Växjö Lakers', 32, 3, 10, 13, 14, 'Regular'),
        ('Leo', 'Sahlin Wallenius', 'Växjö Lakers', 10, 2, 4, 6, 2, 'Playoff'),
        ('Keegan', 'Lowe', 'Växjö Lakers', 52, 2, 10, 12, 60, 'Regular'),
        ('Keegan', 'Lowe', 'Växjö Lakers', 10, 0, 3, 3, 10, 'Playoff'),
        ('Brian', 'Cooper', 'Växjö Lakers', 45, 2, 8, 10, 77, 'Regular'),
        ('Brian', 'Cooper', 'Växjö Lakers', 10, 1, 2, 3, 2, 'Playoff'),
        ('Hugo', 'Gustafsson', 'Växjö Lakers', 18, 5, 4, 9, 2, 'Regular'),
        ('Hugo', 'Gustafsson', 'Växjö Lakers', 10, 3, 2, 5, 0, 'Playoff'),
        ('Petter', 'Granberg', 'Växjö Lakers', 52, 1, 8, 9, 24, 'Regular'),
        ('Petter', 'Granberg', 'Växjö Lakers', 10, 0, 1, 1, 0, 'Playoff'),
        ('Ludvig', 'Nilsson', 'Växjö Lakers', 47, 4, 4, 8, 16, 'Regular'),
        ('Ludvig', 'Nilsson', 'Växjö Lakers', 4, 0, 0, 0, 6, 'Playoff'),
        ('Kalle', 'Kratz', 'Växjö Lakers', 50, 5, 2, 7, 9, 'Regular'),
        ('Kalle', 'Kratz', 'Växjö Lakers', 10, 1, 1, 2, 4, 'Playoff'),
        ('Ville', 'Svensson', 'Växjö Lakers', 40, 2, 4, 6, 6, 'Regular'),
        ('Ville', 'Svensson', 'Växjö Lakers', 7, 0, 0, 0, 0, 'Playoff'),
        ('Erik', 'Andersson', 'Växjö Lakers', 36, 1, 4, 5, 4, 'Regular'),
        ('Erik', 'Andersson', 'Växjö Lakers', 10, 1, 2, 3, 0, 'Playoff'),
        ('Elias', 'Rosén', 'Växjö Lakers', 39, 0, 5, 5, 4, 'Regular'),
        ('Elias', 'Rosén', 'Växjö Lakers', 8, 0, 1, 1, 0, 'Playoff'),
        ('Zach', 'Giuttari', 'Växjö Lakers', 38, 0, 4, 4, 4, 'Regular'),
        ('Zach', 'Giuttari', 'Växjö Lakers', 3, 0, 0, 0, 0, 'Playoff'),
        ('Morgan', 'Anderberg', 'Växjö Lakers', 39, 2, 1, 3, 0, 'Regular'),
        ('Morgan', 'Anderberg', 'Växjö Lakers', 10, 1, 2, 3, 2, 'Playoff'),
        ('Otto', 'Koivula', 'Växjö Lakers', 5, 1, 1, 2, 2, 'Regular'),
        ('Emon', 'Kulmala', 'Växjö Lakers', 1, 0, 0, 0, 0, 'Regular'),
        ('Elias', 'Lindgren', 'Växjö Lakers', 1, 0, 0, 0, 0, 'Regular'),
        ('Olle', 'Tideman', 'Växjö Lakers', 1, 0, 0, 0, 0, 'Regular'),
        ('Albin', 'Laksonen', 'Växjö Lakers', 2, 0, 0, 0, 0, 'Regular'),
        ('Liam', 'Pettersson', 'Växjö Lakers', 2, 0, 0, 0, 0, 'Regular'),
        ('Max', 'Isaksson', 'Växjö Lakers', 3, 0, 0, 0, 0, 'Regular'),
        ('Ola', 'Palme', 'Växjö Lakers', 5, 0, 0, 0, 0, 'Regular'),
        ('Olle', 'Karlsson', 'Växjö Lakers', 5, 0, 0, 0, 2, 'Regular'),

        -- RÖGLE
        ('Felix', 'Nilsson', 'Rögle BK', 52, 14, 26, 40, 14, 'Regular'),
        ('Felix', 'Nilsson', 'Rögle BK', 17, 2, 4, 6, 0, 'Playoff'),
        ('Fredrik', 'Olofsson', 'Rögle BK', 52, 12, 26, 38, 12, 'Regular'),
        ('Fredrik', 'Olofsson', 'Rögle BK', 17, 5, 6, 11, 6, 'Playoff'),
        ('Calle', 'Själin', 'Rögle BK', 48, 7, 28, 35, 32, 'Regular'),
        ('Calle', 'Själin', 'Rögle BK', 17, 2, 8, 10, 8, 'Playoff'),
        ('Leon', 'Bristedt', 'Rögle BK', 49, 14, 15, 29, 74, 'Regular'),
        ('Leon', 'Bristedt', 'Rögle BK', 17, 1, 9, 10, 14, 'Playoff'),
        ('Lucas', 'Ekeståhl Jonsson', 'Rögle BK', 52, 7, 19, 26, 22, 'Regular'),
        ('Lucas', 'Ekeståhl Jonsson', 'Rögle BK', 8, 0, 3, 3, 0, 'Playoff'),
        ('Karson', 'Kuhlman', 'Rögle BK', 52, 13, 12, 25, 8, 'Regular'),
        ('Karson', 'Kuhlman', 'Rögle BK', 17, 3, 4, 7, 0, 'Playoff'),
        ('Lubos', 'Horky', 'Rögle BK', 46, 12, 10, 22, 2, 'Regular'),
        ('Lubos', 'Horky', 'Rögle BK', 17, 2, 6, 8, 2, 'Playoff'),
        ('Daniel', 'Zaar', 'Rögle BK', 47, 10, 12, 22, 20, 'Regular'),
        ('Daniel', 'Zaar', 'Rögle BK', 15, 5, 7, 12, 10, 'Playoff'),
        ('Linus', 'Sandin', 'Rögle BK', 49, 9, 9, 18, 17, 'Regular'),
        ('Linus', 'Sandin', 'Rögle BK', 15, 6, 3, 9, 0, 'Playoff'),
        ('Paul', 'LaDue', 'Rögle BK', 47, 6, 12, 18, 12, 'Regular'),
        ('Paul', 'LaDue', 'Rögle BK', 17, 3, 1, 4, 10, 'Playoff'),
        ('Albin', 'Sundsvik', 'Rögle BK', 52, 6, 11, 17, 10, 'Regular'),
        ('Albin', 'Sundsvik', 'Rögle BK', 17, 5, 5, 10, 8, 'Playoff'),
        ('Dennis', 'Everberg', 'Rögle BK', 48, 9, 7, 16, 18, 'Regular'),
        ('Dennis', 'Everberg', 'Rögle BK', 13, 2, 4, 6, 10, 'Playoff'),
        ('Calvin', 'de Haan', 'Rögle BK', 46, 3, 13, 16, 47, 'Regular'),
        ('Calvin', 'de Haan', 'Rögle BK', 15, 0, 9, 9, 4, 'Playoff'),
        ('Mark', 'Friedman', 'Rögle BK', 47, 3, 12, 15, 68, 'Regular'),
        ('Mark', 'Friedman', 'Rögle BK', 12, 3, 1, 4, 30, 'Playoff'),
        ('Josh', 'Dickinson', 'Rögle BK', 36, 9, 5, 14, 20, 'Regular'),
        ('Josh', 'Dickinson', 'Rögle BK', 12, 2, 4, 6, 2, 'Playoff'),
        ('Anton', 'Bengtsson', 'Rögle BK', 40, 5, 9, 14, 18, 'Regular'),
        ('Anton', 'Bengtsson', 'Rögle BK', 17, 4, 3, 7, 27, 'Playoff'),
        ('Filip', 'Johansson', 'Rögle BK', 40, 5, 8, 13, 10, 'Regular'),
        ('Filip', 'Johansson', 'Rögle BK', 17, 4, 2, 6, 6, 'Playoff'),
        ('Simon', 'Zether', 'Rögle BK', 40, 1, 8, 9, 12, 'Regular'),
        ('Simon', 'Zether', 'Rögle BK', 6, 0, 0, 0, 0, 'Playoff'),
        ('Isac', 'Solberg', 'Rögle BK', 42, 5, 2, 7, 6, 'Regular'),
        ('Isac', 'Solberg', 'Rögle BK', 16, 1, 1, 2, 0, 'Playoff'),
        ('Linus', 'Sjödin', 'Rögle BK', 33, 3, 4, 7, 6, 'Regular'),
        ('Linus', 'Sjödin', 'Rögle BK', 17, 0, 2, 2, 4, 'Playoff'),
        ('Mattias', 'Göransson', 'Rögle BK', 27, 0, 6, 6, 8, 'Regular'),
        ('Mattias', 'Göransson', 'Rögle BK', 16, 1, 3, 4, 6, 'Playoff'),
        ('Gregor', 'Biber', 'Rögle BK', 38, 1, 1, 2, 12, 'Regular'),
        ('Gregor', 'Biber', 'Rögle BK', 15, 0, 0, 0, 2, 'Playoff'),
        ('Marvin', 'Järvinen', 'Rögle BK', 15, 1, 0, 1, 2, 'Regular'),
        ('Marvin', 'Järvinen', 'Rögle BK', 5, 0, 0, 0, 0, 'Playoff'),
        ('Johannes', 'Neumann', 'Rögle BK', 3, 0, 0, 0, 0, 'Regular'),
        ('Johannes', 'Neumann', 'Rögle BK', 1, 0, 0, 0, 0, 'Playoff'),
        ('Nils', 'Bartholdsson', 'Rögle BK', 5, 0, 0, 0, 0, 'Regular'),
        ('Nils', 'Bartholdsson', 'Rögle BK', 3, 0, 0, 0, 0, 'Playoff'),
        ('Love', 'Gath', 'Rögle BK', 8, 0, 0, 0, 0, 'Regular'),
        ('Isak', 'Norlin', 'Rögle BK', 16, 0, 0, 0, 0, 'Regular'),
        ('Isak', 'Norlin', 'Rögle BK', 2, 0, 0, 0, 0, 'Playoff'),

        -- FÄRJESTAD
        ('Viktor', 'Lodin', 'Färjestad BK', 49, 12, 34, 46, 44, 'Regular'),
        ('Viktor', 'Lodin', 'Färjestad BK', 5, 2, 3, 5, 8, 'Playoff'),
        ('Luke', 'Philp', 'Färjestad BK', 52, 13, 22, 35, 18, 'Regular'),
        ('Luke', 'Philp', 'Färjestad BK', 5, 0, 2, 2, 2, 'Playoff'),
        ('Per', 'Åslund', 'Färjestad BK', 51, 16, 11, 27, 61, 'Regular'),
        ('Per', 'Åslund', 'Färjestad BK', 7, 1, 2, 3, 0, 'Playoff'),
        ('Radim', 'Zohorna', 'Färjestad BK', 47, 9, 18, 27, 22, 'Regular'),
        ('Radim', 'Zohorna', 'Färjestad BK', 7, 1, 2, 3, 4, 'Playoff'),
        ('Marian', 'Studenic', 'Färjestad BK', 51, 8, 19, 27, 65, 'Regular'),
        ('Marian', 'Studenic', 'Färjestad BK', 5, 1, 1, 2, 4, 'Playoff'),
        ('Axel', 'Bergkvist', 'Färjestad BK', 52, 7, 18, 25, 12, 'Regular'),
        ('Axel', 'Bergkvist', 'Färjestad BK', 7, 1, 2, 3, 4, 'Playoff'),
        ('Joakim', 'Nygård', 'Färjestad BK', 52, 10, 10, 20, 4, 'Regular'),
        ('Joakim', 'Nygård', 'Färjestad BK', 7, 0, 0, 0, 4, 'Playoff'),
        ('David', 'Tomasek', 'Färjestad BK', 19, 8, 11, 19, 10, 'Regular'),
        ('David', 'Tomasek', 'Färjestad BK', 7, 5, 0, 5, 2, 'Playoff'),
        ('Filip', 'Roos', 'Färjestad BK', 52, 8, 11, 19, 4, 'Regular'),
        ('Filip', 'Roos', 'Färjestad BK', 7, 0, 3, 3, 4, 'Playoff'),
        ('Magnus', 'Nygren', 'Färjestad BK', 47, 6, 11, 17, 16, 'Regular'),
        ('Magnus', 'Nygren', 'Färjestad BK', 7, 0, 1, 1, 8, 'Playoff'),
        ('Joel', 'Kellman', 'Färjestad BK', 45, 10, 6, 16, 12, 'Regular'),
        ('Joel', 'Kellman', 'Färjestad BK', 7, 0, 2, 2, 0, 'Playoff'),
        ('Oskar', 'Steen', 'Färjestad BK', 40, 6, 10, 16, 14, 'Regular'),
        ('Oskar', 'Steen', 'Färjestad BK', 7, 2, 1, 3, 4, 'Playoff'),
        ('Linus', 'Johansson', 'Färjestad BK', 35, 4, 11, 15, 22, 'Regular'),
        ('Linus', 'Johansson', 'Färjestad BK', 7, 1, 4, 5, 12, 'Playoff'),
        ('Adam', 'Ollas Mattsson', 'Färjestad BK', 52, 1, 12, 13, 22, 'Regular'),
        ('Adam', 'Ollas Mattsson', 'Färjestad BK', 7, 0, 0, 0, 0, 'Playoff'),
        ('Jack', 'Berglund', 'Färjestad BK', 40, 7, 5, 12, 26, 'Regular'),
        ('Jack', 'Berglund', 'Färjestad BK', 7, 0, 3, 3, 2, 'Playoff'),
        ('Christoffer', 'Jansson', 'Färjestad BK', 48, 4, 8, 12, 8, 'Regular'),
        ('Christoffer', 'Jansson', 'Färjestad BK', 5, 0, 0, 0, 2, 'Playoff'),
        ('Lucas', 'Forsell', 'Färjestad BK', 50, 5, 5, 10, 20, 'Regular'),
        ('Lucas', 'Forsell', 'Färjestad BK', 7, 1, 1, 2, 2, 'Playoff'),
        ('Emil', 'Alba', 'Färjestad BK', 45, 2, 7, 9, 35, 'Regular'),
        ('Emil', 'Alba', 'Färjestad BK', 2, 1, 0, 1, 0, 'Playoff'),
        ('Gabriel', 'Carlsson', 'Färjestad BK', 46, 2, 7, 9, 28, 'Regular'),
        ('Gabriel', 'Carlsson', 'Färjestad BK', 7, 0, 0, 0, 6, 'Playoff'),
        ('Albert', 'Wikman', 'Färjestad BK', 46, 3, 2, 5, 6, 'Regular'),
        ('Albert', 'Wikman', 'Färjestad BK', 7, 0, 0, 0, 0, 'Playoff'),
        ('Ronald', 'Knot', 'Färjestad BK', 33, 2, 2, 4, 6, 'Regular'),

        ('Nick', 'Leivermann', 'Färjestad BK', 9, 0, 3, 3, 4, 'Regular'),
        ('Nick', 'Leivermann', 'Färjestad BK', 7, 0, 1, 1, 4, 'Playoff'),
        ('August', 'Tornberg', 'Färjestad BK', 6, 1, 1, 2, 2, 'Regular'),
        ('Noel', 'Fransén', 'Färjestad BK', 13, 1, 1, 2, 6, 'Regular'),
        ('Samuel', 'Eriksson', 'Färjestad BK', 1, 0, 0, 0, 0, 'Regular'),
        ('Rasmus', 'Röing', 'Färjestad BK', 1, 0, 0, 0, 0, 'Regular'),
        ('Åke', 'Stakkestad', 'Färjestad BK', 1, 0, 0, 0, 0, 'Regular'),
        ('Hampus', 'Plato', 'Färjestad BK', 1, 0, 0, 0, 0, 'Regular'),
        ('Måns', 'Gudmundsson', 'Färjestad BK', 1, 0, 0, 0, 0, 'Regular'),
        ('Oliver', 'Marcelius', 'Färjestad BK', 2, 0, 0, 0, 0, 'Regular'),
        ('Joe', 'Wahlund', 'Färjestad BK', 4, 0, 0, 0, 0, 'Regular'),
        ('Elias', 'Eriksson', 'Färjestad BK', 4, 0, 0, 0, 0, 'Regular'),
        ('Elias', 'Eriksson', 'Färjestad BK', 1, 0, 0, 0, 0, 'Playoff'),
        ('Mikkel', 'Eriksen', 'Färjestad BK', 15, 0, 0, 0, 0, 'Regular'),
        ('Mikkel', 'Eriksen', 'Färjestad BK', 5, 0, 0, 0, 0, 'Playoff'),
        ('Wille', 'Johansson', 'Färjestad BK', 18, 0, 0, 0, 2, 'Regular'),

        -- BRYNÄS
        ('Jakob', 'Silfverberg', 'Brynäs IF', 52, 20, 23, 43, 44, 'Regular'),
        ('Jakob', 'Silfverberg', 'Brynäs IF', 5, 3, 1, 4, 0, 'Playoff'),
        ('Johannes', 'Kinnvall', 'Brynäs IF', 51, 12, 29, 41, 16, 'Regular'),
        ('Johannes', 'Kinnvall', 'Brynäs IF', 5, 1, 5, 6, 0, 'Playoff'),
        ('Anton', 'Rödin', 'Brynäs IF', 48, 11, 23, 34, 26, 'Regular'),
        ('Anton', 'Rödin', 'Brynäs IF', 5, 1, 4, 5, 2, 'Playoff'),
        ('Kieffer', 'Bellows', 'Brynäs IF', 52, 15, 15, 30, 33, 'Regular'),
        ('Kieffer', 'Bellows', 'Brynäs IF', 5, 0, 2, 2, 22, 'Playoff'),
        ('Johan', 'Larsson', 'Brynäs IF', 51, 12, 18, 30, 48, 'Regular'),
        ('Johan', 'Larsson', 'Brynäs IF', 5, 2, 0, 2, 0, 'Playoff'),
        ('Nicklas', 'Bäckström', 'Brynäs IF', 45, 3, 27, 30, 12, 'Regular'),
        ('Nicklas', 'Bäckström', 'Brynäs IF', 5, 0, 2, 2, 0, 'Playoff'),
        ('Bobby', 'Trivigno', 'Brynäs IF', 50, 8, 17, 25, 22, 'Regular'),
        ('Bobby', 'Trivigno', 'Brynäs IF', 5, 1, 1, 2, 2, 'Playoff'),
        ('Oskar', 'Lindblom', 'Brynäs IF', 49, 13, 9, 22, 10, 'Regular'),
        ('Oskar', 'Lindblom', 'Brynäs IF', 4, 2, 0, 2, 25, 'Playoff'),
        ('Lucas', 'Pettersson', 'Brynäs IF', 41, 10, 10, 20, 0, 'Regular'),
        ('Lucas', 'Pettersson', 'Brynäs IF', 5, 0, 4, 4, 2, 'Playoff'),
        ('Linus', 'Ölund', 'Brynäs IF', 51, 8, 9, 17, 37, 'Regular'),
        ('Linus', 'Ölund', 'Brynäs IF', 2, 0, 0, 0, 0, 'Playoff'),
        ('Axel', 'Andersson', 'Brynäs IF', 41, 7, 10, 17, 6, 'Regular'),
        ('Axel', 'Andersson', 'Brynäs IF', 5, 0, 0, 0, 4, 'Playoff'),
        ('Axel', 'Jonsson-Fjällby', 'Brynäs IF', 52, 6, 10, 16, 14, 'Regular'),
        ('Axel', 'Jonsson-Fjällby', 'Brynäs IF', 5, 1, 0, 1, 0, 'Playoff'),
        ('Michal', 'Kempný', 'Brynäs IF', 39, 7, 8, 15, 18, 'Regular'),
        ('Michal', 'Kempný', 'Brynäs IF', 5, 0, 1, 1, 0, 'Playoff'),
        ('Robert', 'Hägg', 'Brynäs IF', 52, 4, 11, 15, 60, 'Regular'),
        ('Robert', 'Hägg', 'Brynäs IF', 5, 0, 0, 0, 2, 'Playoff'),
        ('Jack', 'Kopacka', 'Brynäs IF', 45, 7, 7, 14, 2, 'Regular'),
        ('Jack', 'Kopacka', 'Brynäs IF', 3, 0, 0, 0, 0, 'Playoff'),
        ('Mattias', 'Norlinder', 'Brynäs IF', 48, 4, 9, 13, 8, 'Regular'),
        ('Mattias', 'Norlinder', 'Brynäs IF', 5, 1, 1, 2, 20, 'Playoff'),
        ('Tyler', 'Vesel', 'Brynäs IF', 51, 3, 6, 9, 6, 'Regular'),
        ('Tyler', 'Vesel', 'Brynäs IF', 5, 0, 1, 1, 0, 'Playoff'),
        ('Greg', 'Scott', 'Brynäs IF', 47, 4, 3, 7, 8, 'Regular'),
        ('Greg', 'Scott', 'Brynäs IF', 5, 0, 0, 0, 2, 'Playoff'),
        ('Christian', 'Djoos', 'Brynäs IF', 18, 0, 3, 3, 2, 'Regular'),
        ('Simon', 'Bertilsson', 'Brynäs IF', 26, 0, 3, 3, 6, 'Regular'),
        ('Simon', 'Bertilsson', 'Brynäs IF', 5, 0, 1, 1, 0, 'Playoff'),
        ('Luke', 'Witkowski', 'Brynäs IF', 27, 0, 2, 2, 8, 'Regular'),
        ('Luke', 'Witkowski', 'Brynäs IF', 2, 0, 0, 0, 2, 'Playoff'),
        ('Gustav', 'Hillström', 'Brynäs IF', 27, 0, 1, 1, 0, 'Regular'),
        ('Albin', 'Udd', 'Brynäs IF', 1, 0, 0, 0, 0, 'Regular'),
        ('Leo', 'Sundqvist', 'Brynäs IF', 11, 0, 0, 0, 0, 'Regular'),
        ('Leo', 'Sundqvist', 'Brynäs IF', 3, 0, 0, 0, 2, 'Playoff'),
        ('Michal', 'Svrcek', 'Brynäs IF', 12, 0, 0, 0, 0, 'Regular'),
        ('Michal', 'Svrcek', 'Brynäs IF', 3, 0, 0, 0, 0, 'Playoff'),
        ('Aron', 'Dahlqvist', 'Brynäs IF', 14, 0, 0, 0, 4, 'Regular'),
        ('Aron', 'Dahlqvist', 'Brynäs IF', 1, 0, 0, 0, 0, 'Playoff'),
        ('Victor', 'Hedin Raftheim', 'Brynäs IF', 28, 0, 0, 0, 4, 'Regular'),

        -- MALMÖ
        ('Janne', 'Kuokkanen', 'Malmö Redhawks', 48, 13, 32, 45, 51, 'Regular'),
        ('Janne', 'Kuokkanen', 'Malmö Redhawks', 8, 0, 3, 3, 6, 'Playoff'),
        ('Carl', 'Persson', 'Malmö Redhawks', 49, 23, 18, 41, 22, 'Regular'),
        ('Carl', 'Persson', 'Malmö Redhawks', 8, 1, 0, 1, 4, 'Playoff'),
        ('Robin', 'Salo', 'Malmö Redhawks', 52, 7, 33, 40, 16, 'Regular'),
        ('Robin', 'Salo', 'Malmö Redhawks', 8, 1, 1, 2, 0, 'Playoff'),
        ('Lauri', 'Pajuniemi', 'Malmö Redhawks', 51, 16, 22, 38, 54, 'Regular'),
        ('Lauri', 'Pajuniemi', 'Malmö Redhawks', 8, 1, 1, 2, 4, 'Playoff'),
        ('Axel', 'Sundberg', 'Malmö Redhawks', 49, 14, 20, 34, 10, 'Regular'),
        ('Axel', 'Sundberg', 'Malmö Redhawks', 8, 1, 0, 1, 0, 'Playoff'),
        ('Fredrik', 'Händemark', 'Malmö Redhawks', 51, 18, 11, 29, 28, 'Regular'),
        ('Fredrik', 'Händemark', 'Malmö Redhawks', 8, 1, 0, 1, 10, 'Playoff'),
        ('Robin', 'Hanzl', 'Malmö Redhawks', 39, 7, 19, 26, 18, 'Regular'),
        ('Robin', 'Hanzl', 'Malmö Redhawks', 8, 0, 5, 5, 2, 'Playoff'),
        ('Linus', 'Öberg', 'Malmö Redhawks', 52, 13, 5, 18, 14, 'Regular'),
        ('Linus', 'Öberg', 'Malmö Redhawks', 8, 2, 2, 4, 2, 'Playoff'),
        ('Topi', 'Niemelä', 'Malmö Redhawks', 52, 4, 14, 18, 14, 'Regular'),
        ('Topi', 'Niemelä', 'Malmö Redhawks', 8, 1, 2, 3, 6, 'Playoff'),
        ('Eemil', 'Viro', 'Malmö Redhawks', 52, 5, 11, 16, 20, 'Regular'),
        ('Eemil', 'Viro', 'Malmö Redhawks', 8, 0, 1, 1, 4, 'Playoff'),
        ('Seth', 'Barton', 'Malmö Redhawks', 47, 4, 12, 16, 18, 'Regular'),
        ('Seth', 'Barton', 'Malmö Redhawks', 7, 0, 1, 1, 0, 'Playoff'),
        ('Petter', 'Vesterheim', 'Malmö Redhawks', 51, 4, 9, 13, 8, 'Regular'),
        ('Petter', 'Vesterheim', 'Malmö Redhawks', 8, 1, 3, 4, 0, 'Playoff'),
        ('Thomas', 'Berg-Paulsen', 'Malmö Redhawks', 40, 4, 8, 12, 14, 'Regular'),
        ('Isac', 'Nilsson', 'Malmö Redhawks', 44, 3, 5, 8, 0, 'Regular'),
        ('Isac', 'Nilsson', 'Malmö Redhawks', 8, 0, 2, 2, 0, 'Playoff'),
        ('William', 'von Barnekow', 'Malmö Redhawks', 45, 3, 5, 8, 12, 'Regular'),
        ('William', 'von Barnekow', 'Malmö Redhawks', 8, 2, 1, 3, 0, 'Playoff'),
        ('Joona', 'Ikonen', 'Malmö Redhawks', 52, 2, 6, 8, 14, 'Regular'),
        ('Joona', 'Ikonen', 'Malmö Redhawks', 8, 2, 0, 2, 0, 'Playoff'),
        ('Filip', 'Björkman', 'Malmö Redhawks', 27, 2, 2, 4, 12, 'Regular'),
        ('Filip', 'Björkman', 'Malmö Redhawks', 8, 1, 0, 1, 2, 'Playoff'),
        ('Martin', 'Schreiber', 'Malmö Redhawks', 50, 0, 3, 3, 43, 'Regular'),
        ('Martin', 'Schreiber', 'Malmö Redhawks', 6, 0, 0, 0, 4, 'Playoff'),
        ('Elia', 'Pedrotti', 'Malmö Redhawks', 20, 0, 2, 2, 4, 'Regular'),
        ('Elia', 'Pedrotti', 'Malmö Redhawks', 8, 0, 1, 1, 0, 'Playoff'),
        ('Kalle', 'Hemström', 'Malmö Redhawks', 29, 1, 0, 1, 4, 'Regular'),
        ('Kalle', 'Hemström', 'Malmö Redhawks', 5, 0, 0, 0, 2, 'Playoff'),
        ('Isac', 'Born', 'Malmö Redhawks', 9, 0, 1, 1, 4, 'Regular'),
        ('Johan', 'Ivarsson', 'Malmö Redhawks', 40, 0, 1, 1, 25, 'Regular'),
        ('Isac', 'Pagels', 'Malmö Redhawks', 0, 0, 0, 0, 0, 'Regular'),
        ('Isac', 'Pagels', 'Malmö Redhawks', 2, 0, 0, 0, 0, 'Playoff'),
        ('Oliver', 'Rosvall', 'Malmö Redhawks', 1, 0, 0, 0, 0, 'Regular'),
        ('Carl-Johan', 'Lerby', 'Malmö Redhawks', 1, 0, 0, 0, 0, 'Regular'),
        ('Freddie', 'Larsson', 'Malmö Redhawks', 3, 0, 0, 0, 0, 'Regular'),
        ('Sebastian', 'Wännström', 'Malmö Redhawks', 3, 0, 0, 0, 0, 'Regular'),
        ('Patrik', 'Norén', 'Malmö Redhawks', 4, 0, 0, 0, 0, 'Regular'),
        ('Viktor', 'Olofsson', 'Malmö Redhawks', 4, 0, 0, 0, 0, 'Regular'),
        ('Viktor', 'Olofsson', 'Malmö Redhawks', 4, 0, 0, 0, 0, 'Playoff'),
        ('Joseph', 'Berger', 'Malmö Redhawks', 15, 0, 0, 0, 4, 'Regular'),
        ('Maximilian', 'Eisenmenger', 'Malmö Redhawks', 26, 0, 0, 0, 8, 'Regular'),
        ('Felix', 'Carell', 'Malmö Redhawks', 31, 0, 0, 0, 4, 'Regular'),
        ('Felix', 'Carell', 'Malmö Redhawks', 8, 0, 2, 2, 0, 'Playoff'),

        -- DJURGÅRDEN
        ('Joey', 'LaLeggia', 'Djurgårdens IF', 50, 13, 27, 40, 10, 'Regular'),
        ('Joey', 'LaLeggia', 'Djurgårdens IF', 3, 0, 1, 1, 0, 'Playoff'),
        ('Joe', 'Snively', 'Djurgårdens IF', 52, 15, 24, 39, 18, 'Regular'),
        ('Joe', 'Snively', 'Djurgårdens IF', 3, 0, 0, 0, 0, 'Playoff'),
        ('Charles', 'Hudon', 'Djurgårdens IF', 40, 15, 16, 31, 18, 'Regular'),
        ('Charles', 'Hudon', 'Djurgårdens IF', 3, 0, 0, 0, 0, 'Playoff'),
        ('Anton', 'Frondell', 'Djurgårdens IF', 43, 20, 8, 28, 16, 'Regular'),
        ('Anton', 'Frondell', 'Djurgårdens IF', 3, 1, 1, 2, 0, 'Playoff'),
        ('Colby', 'Sissons', 'Djurgårdens IF', 51, 4, 21, 25, 28, 'Regular'),
        ('Colby', 'Sissons', 'Djurgårdens IF', 3, 1, 0, 1, 2, 'Playoff'),
        ('Victor', 'Eklund', 'Djurgårdens IF', 43, 6, 18, 24, 22, 'Regular'),
        ('Victor', 'Eklund', 'Djurgårdens IF', 3, 0, 3, 3, 4, 'Playoff'),
        ('Mathias Emilio', 'Pettersen', 'Djurgårdens IF', 48, 4, 17, 21, 47, 'Regular'),
        ('Mathias Emilio', 'Pettersen', 'Djurgårdens IF', 3, 0, 0, 0, 6, 'Playoff'),
        ('Jacob', 'Josefson', 'Djurgårdens IF', 31, 5, 12, 17, 12, 'Regular'),
        ('Jacob', 'Josefson', 'Djurgårdens IF', 3, 1, 0, 1, 2, 'Playoff'),
        ('Viggo', 'Björck', 'Djurgårdens IF', 42, 6, 9, 15, 12, 'Regular'),
        ('Viggo', 'Björck', 'Djurgårdens IF', 3, 1, 2, 3, 0, 'Playoff'),
        ('Marcus', 'Krüger', 'Djurgårdens IF', 40, 5, 10, 15, 8, 'Regular'),
        ('Marcus', 'Krüger', 'Djurgårdens IF', 1, 0, 0, 0, 0, 'Playoff'),
        ('Gustav', 'Lindström', 'Djurgårdens IF', 46, 5, 9, 14, 26, 'Regular'),
        ('Gustav', 'Lindström', 'Djurgårdens IF', 3, 0, 1, 1, 2, 'Playoff'),
        ('Håvard Østrem', 'Salsten', 'Djurgårdens IF', 49, 7, 6, 13, 33, 'Regular'),
        ('Håvard Østrem', 'Salsten', 'Djurgårdens IF', 3, 0, 0, 0, 2, 'Playoff'),
        ('Philip', 'Holm', 'Djurgårdens IF', 49, 5, 8, 13, 20, 'Regular'),
        ('Philip', 'Holm', 'Djurgårdens IF', 3, 0, 1, 1, 2, 'Playoff'),
        ('David', 'Blomgren', 'Djurgårdens IF', 50, 6, 6, 12, 12, 'Regular'),
        ('David', 'Blomgren', 'Djurgårdens IF', 3, 0, 1, 1, 0, 'Playoff'),
        ('Oula', 'Palve', 'Djurgårdens IF', 18, 3, 7, 10, 12, 'Regular'),
        ('Oula', 'Palve', 'Djurgårdens IF', 2, 0, 0, 0, 0, 'Playoff'),
        ('Jesper', 'Pettersson', 'Djurgårdens IF', 51, 3, 7, 10, 30, 'Regular'),
        ('Jesper', 'Pettersson', 'Djurgårdens IF', 3, 0, 0, 0, 2, 'Playoff'),
        ('Oliver', 'Kylington', 'Djurgårdens IF', 25, 2, 6, 8, 10, 'Regular'),
        ('Oliver', 'Kylington', 'Djurgårdens IF', 3, 0, 0, 0, 0, 'Playoff'),
        ('Jesse', 'Ylönen', 'Djurgårdens IF', 24, 3, 4, 7, 33, 'Regular'),
        ('Albin', 'Grewe', 'Djurgårdens IF', 37, 2, 4, 6, 29, 'Regular'),
        ('Ludvig', 'Rensfeldt', 'Djurgårdens IF', 51, 2, 2, 4, 8, 'Regular'),
        ('Ludvig', 'Rensfeldt', 'Djurgårdens IF', 3, 1, 0, 1, 0, 'Playoff'),
        ('Valtteri', 'Pulli', 'Djurgårdens IF', 30, 1, 3, 4, 6, 'Regular'),
        ('August', 'Berg', 'Djurgårdens IF', 23, 2, 0, 2, 6, 'Regular'),
        ('Hugo', 'Blixt', 'Djurgårdens IF', 36, 1, 1, 2, 32, 'Regular'),
        ('Hugo', 'Blixt', 'Djurgårdens IF', 3, 0, 0, 0, 2, 'Playoff'),
        ('Daniel', 'Brodin', 'Djurgårdens IF', 24, 1, 0, 1, 0, 'Regular'),
        ('William', 'Wåhlén', 'Djurgårdens IF', 2, 0, 1, 1, 0, 'Regular'),
        ('Marcus', 'Nordmark', 'Djurgårdens IF', 8, 0, 1, 1, 2, 'Regular'),
        ('Linus', 'Klasen', 'Djurgårdens IF', 9, 0, 1, 1, 4, 'Regular'),
        ('Theo', 'Stockselius', 'Djurgårdens IF', 16, 0, 1, 1, 6, 'Regular'),
        ('Theo', 'Stockselius', 'Djurgårdens IF', 3, 0, 0, 0, 0, 'Playoff'),
        ('Arvid', 'Costmar', 'Djurgårdens IF', 29, 0, 1, 1, 12, 'Regular'),
        ('Fred', 'Nord', 'Djurgårdens IF', 1, 0, 0, 0, 0, 'Regular'),
        ('Arvid', 'Drott', 'Djurgårdens IF', 1, 0, 0, 0, 0, 'Regular'),
        ('Samuel', 'Solem', 'Djurgårdens IF', 8, 0, 0, 0, 2, 'Regular'),
        ('Samuel', 'Solem', 'Djurgårdens IF', 3, 0, 0, 0, 0, 'Playoff'),

        -- ÖREBRO
        ('Patrik', 'Karlkvist', 'Örebro HK', 52, 15, 35, 50, 14, 'Regular'),
        ('Patrik', 'Karlkvist', 'Örebro HK', 3, 0, 3, 3, 0, 'Playoff'),
        ('David', 'Quenneville', 'Örebro HK', 52, 16, 28, 44, 14, 'Regular'),
        ('David', 'Quenneville', 'Örebro HK', 3, 0, 3, 3, 0, 'Playoff'),
        ('Patrik', 'Puistola', 'Örebro HK', 50, 14, 22, 36, 19, 'Regular'),
        ('Patrik', 'Puistola', 'Örebro HK', 3, 1, 1, 2, 2, 'Playoff'),
        ('Kalle', 'Kossila', 'Örebro HK', 43, 11, 23, 34, 18, 'Regular'),
        ('Kalle', 'Kossila', 'Örebro HK', 3, 4, 1, 5, 0, 'Playoff'),
        ('Luke', 'Martin', 'Örebro HK', 50, 7, 16, 23, 41, 'Regular'),
        ('Luke', 'Martin', 'Örebro HK', 3, 0, 0, 0, 0, 'Playoff'),
        ('Noah', 'Steen', 'Örebro HK', 52, 12, 10, 22, 18, 'Regular'),
        ('Noah', 'Steen', 'Örebro HK', 3, 0, 0, 0, 0, 'Playoff'),
        ('Egor', 'Polin', 'Örebro HK', 50, 10, 11, 21, 8, 'Regular'),
        ('Egor', 'Polin', 'Örebro HK', 3, 0, 0, 0, 0, 'Playoff'),
        ('Milton', 'Oscarson', 'Örebro HK', 52, 10, 9, 19, 20, 'Regular'),
        ('Milton', 'Oscarson', 'Örebro HK', 3, 0, 0, 0, 0, 'Playoff'),
        ('Teemu', 'Turunen', 'Örebro HK', 29, 7, 7, 14, 6, 'Regular'),
        ('Teemu', 'Turunen', 'Örebro HK', 3, 0, 2, 2, 0, 'Playoff'),
        ('Christopher', 'Mastomäki', 'Örebro HK', 52, 6, 8, 14, 53, 'Regular'),
        ('Christopher', 'Mastomäki', 'Örebro HK', 3, 0, 0, 0, 0, 'Playoff'),
        ('William', 'Wikman', 'Örebro HK', 49, 5, 8, 13, 4, 'Regular'),
        ('William', 'Wikman', 'Örebro HK', 2, 0, 0, 0, 2, 'Playoff'),
        ('Linus', 'Arnesson', 'Örebro HK', 50, 4, 9, 13, 16, 'Regular'),
        ('Linus', 'Arnesson', 'Örebro HK', 3, 0, 0, 0, 0, 'Playoff'),
        ('Peetro', 'Seppälä', 'Örebro HK', 51, 1, 9, 10, 14, 'Regular'),
        ('Peetro', 'Seppälä', 'Örebro HK', 1, 0, 0, 0, 0, 'Playoff'),
        ('Glenn', 'Gustafsson', 'Örebro HK', 52, 4, 5, 9, 18, 'Regular'),
        ('Glenn', 'Gustafsson', 'Örebro HK', 3, 0, 0, 0, 2, 'Playoff'),
        ('Filip', 'Berglund', 'Örebro HK', 37, 2, 7, 9, 22, 'Regular'),
        ('Filip', 'Berglund', 'Örebro HK', 3, 0, 1, 1, 6, 'Playoff'),
        ('Sean', 'Malone', 'Örebro HK', 31, 1, 8, 9, 8, 'Regular'),
        ('Gustav', 'Backström', 'Örebro HK', 52, 4, 4, 8, 14, 'Regular'),
        ('Gustav', 'Backström', 'Örebro HK', 3, 0, 1, 1, 2, 'Playoff'),
        ('Jesse', 'Ylönen', 'Örebro HK', 17, 4, 3, 7, 2, 'Regular'),
        ('Jesse', 'Ylönen', 'Örebro HK', 3, 0, 1, 1, 0, 'Playoff'),
        ('Sampo', 'Ranta', 'Örebro HK', 16, 3, 3, 6, 10, 'Regular'),
        ('Sampo', 'Ranta', 'Örebro HK', 3, 0, 0, 0, 0, 'Playoff'),
        ('Melvin', 'Fernström', 'Örebro HK', 36, 3, 1, 4, 6, 'Regular'),
        ('Kalle', 'Miketinac', 'Örebro HK', 17, 0, 2, 2, 0, 'Regular'),
        ('Kalle', 'Miketinac', 'Örebro HK', 3, 2, 0, 2, 0, 'Playoff'),
        ('Liam', 'Danielsson', 'Örebro HK', 17, 0, 2, 2, 2, 'Regular'),
        ('Svante', 'Sjödin', 'Örebro HK', 26, 0, 2, 2, 0, 'Regular'),
        ('Svante', 'Sjödin', 'Örebro HK', 3, 0, 0, 0, 0, 'Playoff'),
        ('Juuso', 'Vainio', 'Örebro HK', 28, 0, 2, 2, 4, 'Regular'),
        ('Juuso', 'Vainio', 'Örebro HK', 2, 0, 0, 0, 0, 'Playoff'),
        ('Theodor', 'Hallquisth', 'Örebro HK', 8, 0, 1, 1, 2, 'Regular'),
        ('Niklas', 'Nilsson', 'Örebro HK', 29, 0, 1, 1, 4, 'Regular'),
        ('Niklas', 'Nilsson', 'Örebro HK', 3, 0, 1, 1, 0, 'Playoff'),
        ('Philip', 'Larsson', 'Örebro HK', 1, 0, 0, 0, 0, 'Regular'),
        ('Felix', 'Färhammar', 'Örebro HK', 2, 0, 0, 0, 0, 'Regular'),
        ('Ludvig', 'Andersson', 'Örebro HK', 2, 0, 0, 0, 0, 'Regular'),
        ('Axel', 'Elfsson', 'Örebro HK', 6, 0, 0, 0, 0, 'Regular'),
        ('Alexander', 'Command', 'Örebro HK', 6, 0, 0, 0, 0, 'Regular'),
        ('Niklas', 'Aaram-Olsen', 'Örebro HK', 16, 0, 0, 0, 0, 'Regular'),

        -- LINKÖPING
        ('Robin', 'Kovács', 'Linköping HC', 50, 23, 24, 47, 49, 'Regular'),
        ('Eskild Bakke', 'Olsen', 'Linköping HC', 51, 11, 21, 32, 10, 'Regular'),
        ('Markus', 'Ljungh', 'Linköping HC', 52, 8, 21, 29, 12, 'Regular'),
        ('Jakub', 'Vrána', 'Linköping HC', 46, 12, 16, 28, 66, 'Regular'),
        ('Nick', 'Shore', 'Linköping HC', 50, 11, 17, 28, 12, 'Regular'),
        ('Fredrik', 'Karlström', 'Linköping HC', 44, 12, 10, 22, 6, 'Regular'),
        ('Christoffer', 'Ehn', 'Linköping HC', 52, 9, 13, 22, 8, 'Regular'),
        ('David', 'Bernhardt', 'Linköping HC', 46, 5, 14, 19, 10, 'Regular'),
        ('Max', 'Martin', 'Linköping HC', 52, 0, 16, 16, 28, 'Regular'),
        ('Zion', 'Nybeck', 'Linköping HC', 52, 5, 7, 12, 6, 'Regular'),
        ('Oscar', 'Fantenberg', 'Linköping HC', 10, 2, 10, 12, 20, 'Regular'),
        ('Johan', 'Södergran', 'Linköping HC', 52, 5, 5, 10, 8, 'Regular'),
        ('Rasmus', 'Rissanen', 'Linköping HC', 48, 1, 8, 9, 24, 'Regular'),
        ('Theodor', 'Lennström', 'Linköping HC', 18, 0, 7, 7, 62, 'Regular'),
        ('Mikko', 'Kokkonen', 'Linköping HC', 44, 0, 7, 7, 6, 'Regular'),
        ('Ty', 'Rattie', 'Linköping HC', 30, 5, 1, 6, 11, 'Regular'),
        ('Jonathan', 'Myrenberg', 'Linköping HC', 48, 2, 4, 6, 10, 'Regular'),
        ('Remi', 'Elie', 'Linköping HC', 7, 4, 0, 4, 4, 'Regular'),
        ('Oliver', 'Johansson', 'Linköping HC', 41, 2, 2, 4, 12, 'Regular'),
        ('Loke', 'Krantz', 'Linköping HC', 30, 1, 1, 2, 16, 'Regular'),
        ('Johan', 'Johnsson', 'Linköping HC', 24, 0, 2, 2, 8, 'Regular'),
        ('Adam', 'Hofbauer', 'Linköping HC', 52, 1, 0, 1, 8, 'Regular'),
        ('Melvin', 'Nilsen', 'Linköping HC', 20, 0, 1, 1, 0, 'Regular'),
        ('Felix', 'Öhrqvist', 'Linköping HC', 23, 0, 1, 1, 6, 'Regular'),
        ('Oscar', 'Emanuelsson', 'Linköping HC', 1, 0, 0, 0, 0, 'Regular'),
        ('Milton', 'Carpenhammar', 'Linköping HC', 3, 0, 0, 0, 0, 'Regular'),
        ('William', 'Proos', 'Linköping HC', 4, 0, 0, 0, 0, 'Regular'),
        ('Wilhelm', 'Hasseluhn', 'Linköping HC', 5, 0, 0, 0, 0, 'Regular'),
        ('Oscar', 'Lawner', 'Linköping HC', 6, 0, 0, 0, 2, 'Regular'),
        ('Edvin', 'Hammarlund', 'Linköping HC', 7, 0, 0, 0, 0, 'Regular'),
        ('Ludvig', 'Larsson', 'Linköping HC', 10, 0, 0, 0, 0, 'Regular'),
        ('Oscar', 'Holmertz', 'Linköping HC', 11, 0, 0, 0, 0, 'Regular'),
        ('Erik', 'Norén', 'Linköping HC', 38, 0, 0, 0, 18, 'Regular'),

        -- TIMRÅ
        ('Jonathan', 'Dahlén', 'Timrå IK', 50, 30, 25, 55, 16, 'Regular'),
        ('Emil', 'Pettersson', 'Timrå IK', 51, 15, 31, 46, 22, 'Regular'),
        ('Eddie', 'Genborg', 'Timrå IK', 43, 9, 16, 25, 24, 'Regular'),
        ('Anton', 'Lander', 'Timrå IK', 50, 10, 12, 22, 18, 'Regular'),
        ('Sebastian', 'Hartmann', 'Timrå IK', 43, 8, 12, 20, 22, 'Regular'),
        ('Marcus', 'Hardegård', 'Timrå IK', 41, 2, 17, 19, 16, 'Regular'),
        ('Anton', 'Heikkinen', 'Timrå IK', 49, 8, 9, 17, 6, 'Regular'),
        ('Erik', 'Walli Walterholm', 'Timrå IK', 50, 5, 11, 16, 47, 'Regular'),
        ('Didrik', 'Strömberg', 'Timrå IK', 48, 3, 12, 15, 38, 'Regular'),
        ('Simon', 'Forsmark', 'Timrå IK', 51, 3, 11, 14, 6, 'Regular'),
        ('Anton', 'Wedin', 'Timrå IK', 32, 5, 7, 12, 2, 'Regular'),
        ('Alfons', 'Freij', 'Timrå IK', 42, 6, 5, 11, 14, 'Regular'),
        ('Linus', 'Nässén', 'Timrå IK', 46, 4, 7, 11, 8, 'Regular'),
        ('Albin', 'Sundin', 'Timrå IK', 51, 4, 5, 9, 20, 'Regular'),
        ('Ludvig', 'Levinsson', 'Timrå IK', 43, 2, 7, 9, 10, 'Regular'),
        ('Per', 'Svensson', 'Timrå IK', 43, 2, 5, 7, 8, 'Regular'),
        ('Linus', 'Eriksson', 'Timrå IK', 43, 2, 5, 7, 12, 'Regular'),
        ('David', 'Lilja', 'Timrå IK', 49, 2, 5, 7, 8, 'Regular'),
        ('Marcus', 'Westfält', 'Timrå IK', 49, 4, 2, 6, 14, 'Regular'),
        ('Anton', 'Lundmark', 'Timrå IK', 23, 2, 3, 5, 2, 'Regular'),
        ('Lukas', 'Pilö', 'Timrå IK', 39, 0, 4, 4, 6, 'Regular'),
        ('Jeremy', 'Boyce', 'Timrå IK', 25, 1, 1, 2, 2, 'Regular'),
        ('Magnus', 'Pääjärvi', 'Timrå IK', 52, 0, 2, 2, 4, 'Regular'),
        ('Tim', 'Erixon', 'Timrå IK', 0, 0, 0, 0, 0, 'Regular'),
        ('Adrian', 'Thun-Hansson', 'Timrå IK', 2, 0, 0, 0, 0, 'Regular'),
        ('Olle', 'Därth', 'Timrå IK', 3, 0, 0, 0, 0, 'Regular'),
        ('William', 'Sörbrand', 'Timrå IK', 5, 0, 0, 0, 0, 'Regular'),
        ('Edwin', 'Annerstedt', 'Timrå IK', 8, 0, 0, 0, 0, 'Regular'),

        -- HV71
        ('Jonathan', 'Ang', 'HV71', 52, 21, 25, 46, 38, 'Regular'),
        ('Jonathan', 'Ang', 'HV71', 4, 1, 3, 4, 4, 'Relegation'),
        ('Axel', 'Rindell', 'HV71', 52, 10, 26, 36, 12, 'Regular'),
        ('Axel', 'Rindell', 'HV71', 3, 0, 1, 1, 25, 'Relegation'),
        ('Riley', 'Woods', 'HV71', 48, 16, 15, 31, 10, 'Regular'),
        ('Riley', 'Woods', 'HV71', 4, 0, 1, 1, 2, 'Relegation'),
        ('Lukas', 'Rousek', 'HV71', 52, 3, 28, 31, 10, 'Regular'),
        ('Lukas', 'Rousek', 'HV71', 4, 1, 0, 1, 0, 'Relegation'),
        ('Hugo', 'Fransson', 'HV71', 52, 11, 15, 26, 14, 'Regular'),
        ('Hugo', 'Fransson', 'HV71', 4, 0, 1, 1, 0, 'Relegation'),
        ('Justin', 'Kloos', 'HV71', 50, 10, 15, 25, 12, 'Regular'),
        ('Justin', 'Kloos', 'HV71', 4, 1, 3, 4, 0, 'Relegation'),
        ('Hugo', 'Pettersson', 'HV71', 43, 12, 8, 20, 2, 'Regular'),
        ('Hugo', 'Pettersson', 'HV71', 4, 3, 0, 3, 0, 'Relegation'),
        ('Aleksi', 'Heponiemi', 'HV71', 28, 6, 12, 18, 4, 'Regular'),
        ('Aleksi', 'Heponiemi', 'HV71', 4, 0, 0, 0, 0, 'Relegation'),
        ('Niklas', 'Hansson', 'HV71', 49, 1, 15, 16, 22, 'Regular'),
        ('Niklas', 'Hansson', 'HV71', 4, 0, 2, 2, 0, 'Relegation'),
        ('Nikola', 'Pasic', 'HV71', 52, 3, 10, 13, 10, 'Regular'),
        ('Nikola', 'Pasic', 'HV71', 4, 0, 0, 0, 0, 'Relegation'),
        ('Mattias', 'Tedenby', 'HV71', 48, 8, 2, 10, 14, 'Regular'),
        ('Mattias', 'Tedenby', 'HV71', 4, 0, 1, 1, 0, 'Relegation'),
        ('Oskar', 'Stål Lyrenäs', 'HV71', 41, 7, 3, 10, 4, 'Regular'),
        ('Oskar', 'Stål Lyrenäs', 'HV71', 4, 0, 0, 0, 0, 'Relegation'),
        ('Andreas', 'Borgman', 'HV71', 35, 3, 7, 10, 32, 'Regular'),
        ('Andreas', 'Borgman', 'HV71', 4, 1, 1, 2, 2, 'Relegation'),
        ('Joona', 'Luoto', 'HV71', 30, 4, 5, 9, 12, 'Regular'),
        ('Joona', 'Luoto', 'HV71', 4, 2, 1, 3, 4, 'Relegation'),
        ('Santeri', 'Hatakka', 'HV71', 34, 1, 8, 9, 26, 'Regular'),
        ('Santeri', 'Hatakka', 'HV71', 4, 0, 0, 0, 8, 'Relegation'),
        ('Olle', 'Alsing', 'HV71', 50, 1, 8, 9, 12, 'Regular'),
        ('Olle', 'Alsing', 'HV71', 4, 0, 1, 1, 0, 'Relegation'),
        ('Lucas', 'Lagerberg Hoen', 'HV71', 43, 4, 4, 8, 14, 'Regular'),
        ('Martin', 'Johnsen', 'HV71', 25, 2, 4, 6, 8, 'Regular'),
        ('Martin', 'Johnsen', 'HV71', 4, 1, 0, 1, 0, 'Relegation'),
        ('William', 'Nilsson Ignberg', 'HV71', 31, 3, 2, 5, 16, 'Regular'),
        ('William', 'Nilsson Ignberg', 'HV71', 4, 0, 1, 1, 4, 'Relegation'),
        ('Hampus', 'Eriksson', 'HV71', 20, 2, 2, 4, 10, 'Regular'),
        ('Hampus', 'Eriksson', 'HV71', 3, 0, 0, 0, 2, 'Relegation'),
        ('Linus', 'Lindström', 'HV71', 44, 2, 2, 4, 8, 'Regular'),
        ('Jamiro', 'Reber', 'HV71', 22, 3, 0, 3, 4, 'Regular'),
        ('Eddie', 'Levin', 'HV71', 2, 1, 2, 3, 0, 'Regular'),
        ('Malte', 'Gustafsson', 'HV71', 27, 0, 3, 3, 4, 'Regular'),
        ('Malte', 'Gustafsson', 'HV71', 4, 0, 0, 0, 2, 'Relegation'),
        ('Isac', 'Brännström', 'HV71', 9, 1, 1, 2, 25, 'Regular'),
        ('Victor', 'Laz', 'HV71', 20, 1, 1, 2, 0, 'Regular'),
        ('Victor', 'Laz', 'HV71', 4, 0, 0, 0, 4, 'Relegation'),
        ('Oscar', 'Davidsson', 'HV71', 15, 0, 1, 1, 0, 'Regular'),
        ('Wille', 'Magnertoft', 'HV71', 20, 0, 1, 1, 2, 'Regular'),
        ('Wille', 'Magnertoft', 'HV71', 1, 0, 0, 0, 0, 'Relegation'),
        ('Gustav', 'Olhaver', 'HV71', 1, 0, 0, 0, 0, 'Regular'),
        ('Tim', 'Lindfors', 'HV71', 1, 0, 0, 0, 0, 'Regular'),
        ('Marcus', 'Limpar Lantz', 'HV71', 1, 0, 0, 0, 0, 'Regular'),
        ('Sigge', 'Lindh', 'HV71', 2, 0, 0, 0, 0, 'Regular'),
        ('Arvid', 'Degerstedt', 'HV71', 2, 0, 0, 0, 0, 'Regular'),
        ('Oscar', 'Söderström', 'HV71', 2, 0, 0, 0, 0, 'Regular'),
        ('Vashek', 'Blanár', 'HV71', 3, 0, 0, 0, 0, 'Regular'),
        ('Hampus', 'Karlsson', 'HV71', 3, 0, 0, 0, 0, 'Regular'),
        ('Noel', 'Skarby', 'HV71', 6, 0, 0, 0, 2, 'Regular'),
        ('Karl', 'Annborn', 'HV71', 17, 0, 0, 0, 4, 'Regular'),
        ('Karl', 'Annborn', 'HV71', 1, 0, 0, 0, 0, 'Relegation'),

        -- LEKSAND
        ('Lukas', 'Vejdemo', 'Leksands IF', 51, 18, 8, 26, 36, 'Regular'),
        ('Lukas', 'Vejdemo', 'Leksands IF', 4, 2, 2, 4, 4, 'Relegation'),
        ('Michael', 'Lindqvist', 'Leksands IF', 31, 6, 19, 25, 20, 'Regular'),
        ('Michael', 'Lindqvist', 'Leksands IF', 4, 2, 1, 3, 2, 'Relegation'),
        ('Peter', 'Cehlárik', 'Leksands IF', 45, 5, 19, 24, 16, 'Regular'),
        ('Peter', 'Cehlárik', 'Leksands IF', 4, 0, 0, 0, 0, 'Relegation'),
        ('Max', 'Véronneau', 'Leksands IF', 40, 7, 13, 20, 2, 'Regular'),
        ('Max', 'Véronneau', 'Leksands IF', 4, 0, 0, 0, 0, 'Relegation'),
        ('Olle', 'Strandell', 'Leksands IF', 52, 5, 14, 19, 10, 'Regular'),
        ('Olle', 'Strandell', 'Leksands IF', 4, 0, 1, 1, 2, 'Relegation'),
        ('Nolan', 'Stevens', 'Leksands IF', 49, 7, 11, 18, 16, 'Regular'),
        ('Nolan', 'Stevens', 'Leksands IF', 4, 0, 1, 1, 2, 'Relegation'),
        ('Anton', 'Johansson', 'Leksands IF', 42, 5, 12, 17, 49, 'Regular'),
        ('Anton', 'Johansson', 'Leksands IF', 3, 0, 0, 0, 27, 'Relegation'),
        ('Gabriel', 'Fortier', 'Leksands IF', 44, 6, 10, 16, 34, 'Regular'),
        ('Gabriel', 'Fortier', 'Leksands IF', 4, 0, 1, 1, 4, 'Relegation'),
        ('Oskar', 'Lang', 'Leksands IF', 49, 8, 7, 15, 39, 'Regular'),
        ('Oskar', 'Lang', 'Leksands IF', 4, 1, 0, 1, 2, 'Relegation'),
        ('Tinus Luc', 'Koblar', 'Leksands IF', 47, 8, 6, 14, 24, 'Regular'),
        ('Tinus Luc', 'Koblar', 'Leksands IF', 4, 0, 0, 0, 2, 'Relegation'),
        ('Andro', 'Kaderli', 'Leksands IF', 49, 4, 9, 13, 76, 'Regular'),
        ('Andro', 'Kaderli', 'Leksands IF', 4, 0, 0, 0, 2, 'Relegation'),
        ('Kalle', 'Östman', 'Leksands IF', 41, 6, 5, 11, 14, 'Regular'),
        ('Kalle', 'Östman', 'Leksands IF', 4, 0, 1, 1, 0, 'Relegation'),
        ('Matt', 'Caito', 'Leksands IF', 50, 4, 7, 11, 30, 'Regular'),
        ('Matt', 'Caito', 'Leksands IF', 4, 0, 0, 0, 0, 'Relegation'),
        ('Joonas', 'Lyytinen', 'Leksands IF', 42, 4, 6, 10, 26, 'Regular'),
        ('Joonas', 'Lyytinen', 'Leksands IF', 1, 0, 0, 0, 0, 'Relegation'),
        ('Alexander', 'Lundqvist', 'Leksands IF', 51, 4, 6, 10, 32, 'Regular'),
        ('Alexander', 'Lundqvist', 'Leksands IF', 4, 0, 0, 0, 0, 'Relegation'),
        ('Arvid', 'Eljas', 'Leksands IF', 41, 3, 6, 9, 16, 'Regular'),
        ('Arvid', 'Eljas', 'Leksands IF', 3, 0, 0, 0, 0, 'Relegation'),
        ('Fred', 'Nilsson', 'Leksands IF', 45, 1, 6, 7, 6, 'Regular'),
        ('Fred', 'Nilsson', 'Leksands IF', 3, 0, 0, 0, 2, 'Relegation'),
        ('Marcus', 'Karlberg', 'Leksands IF', 44, 4, 2, 6, 12, 'Regular'),
        ('Marcus', 'Karlberg', 'Leksands IF', 4, 0, 0, 0, 0, 'Relegation'),
        ('Wiktor', 'Nilsson', 'Leksands IF', 45, 1, 5, 6, 10, 'Regular'),
        ('Wiktor', 'Nilsson', 'Leksands IF', 4, 0, 0, 0, 2, 'Relegation'),
        ('Jon', 'Knuts', 'Leksands IF', 39, 4, 1, 5, 4, 'Regular'),
        ('Stefan', 'Milosevic', 'Leksands IF', 48, 1, 4, 5, 35, 'Regular'),
        ('Stefan', 'Milosevic', 'Leksands IF', 4, 0, 0, 0, 0, 'Relegation'),
        ('Zaki', 'Crookes', 'Leksands IF', 20, 1, 3, 4, 4, 'Regular'),
        ('Zaki', 'Crookes', 'Leksands IF', 1, 0, 0, 0, 0, 'Relegation'),
        ('Victor', 'Johansson', 'Leksands IF', 10, 0, 3, 3, 2, 'Regular'),
        ('Rocky', 'Langvardt', 'Leksands IF', 24, 0, 1, 1, 8, 'Regular'),
        ('Rocky', 'Langvardt', 'Leksands IF', 4, 0, 0, 0, 0, 'Relegation'),
        ('Viggo', 'Lidén', 'Leksands IF', 0, 0, 0, 0, 0, 'Regular'),
        ('Viggo', 'Lidén', 'Leksands IF', 1, 0, 0, 0, 0, 'Relegation'),
        ('Jonas', 'Lagerberg Hoen', 'Leksands IF', 2, 0, 0, 0, 0, 'Regular'),
        ('Pax', 'Kleffner', 'Leksands IF', 2, 0, 0, 0, 0, 'Regular'),
        ('August', 'Lissel', 'Leksands IF', 14, 0, 0, 0, 2, 'Regular'),
        ('Dennis', 'Altörn', 'Leksands IF', 19, 0, 0, 0, 0, 'Regular')

) AS ps 
(
    FirstName, LastName, TeamName, GamesPlayed,  
    Goals, Assists, Points, PenaltyMinutes, Season
)
    JOIN Team t ON t.Name = ps.TeamName
    JOIN Players p
    ON LOWER(TRIM(p.FirstName)) = LOWER(TRIM(ps.FirstName))
        AND LOWER(TRIM(p.LastName)) = LOWER(TRIM(ps.LastName))
        AND p.TeamId = t.TeamId
        AND p.Season = '25/26'
WHERE NOT EXISTS (
    SELECT 1
FROM PlayerStats ps2
WHERE ps2.PlayerId = p.PlayerId
    AND ps2.Season = '25/26'
    AND ps2.Competition = ps.Season);

